### ISSUE TITLE
`escapeWithReference` option and `keepTogether` modifier are confusing

### ISSUE THREAD

**Issue by imkremen** [popperjs/popper.js#230]
Option "escapeWithReference" work only with one axis.
It's related to axis of "placement", i.e. if you have "placement: right", popper will escape on vertical scroll.

Here example https://codepen.io/imkremen/pen/xdEdzv

**Comment by FezVrasta** [comment]
I'm not sure if it's a bug or simply the feature didn't meant to include this use case 🤔

/cc @nadiam84, you wrote that code if I remember correctly?

**Comment by FezVrasta** [comment]
Sorry for the confusion, it's the `keepTogether` modifier that leads to this behavior.

https://codepen.io/FezVrasta/pen/vmXZYx

I think this part of the API is a bit confusing...

**Comment by nadiam84** [comment]
The idea behind 'escape with reference' was that popper behaves like it doesn't have preventOverflow modifier, but flipping still works.

In the first example in this issue the escapeWithReference is `false` and we can see the default popper behavior.

The correct example would be like this: https://codepen.io/nadiam84/pen/PmWpmy
When you scroll up, popper escapes, but flipping still works.

But if you scroll to the left, you'll see that popper just escapes, without flipping. To enable flipping for this axis you need to set `flipVariations` in the `flip` modifier to `true`. https://codepen.io/nadiam84/pen/mmRWwK

I completely agree that this is confusing though...

**Comment by FezVrasta** [comment]
I think we could get rid of the need of `escapeWithReference` if we changed `preventOverflow` to not rely on `flip`..

**Comment by diondiondion** [comment]
Am I correct in thinking that it's not currently possible to get the behaviour of `escapeWithReference: true` while still keeping `preventOverflow` enabled?

I'd like to get the scrolling behaviour shown in this pen: https://codepen.io/imkremen/pen/xdEdzv...

![tooltip-escape](https://user-images.githubusercontent.com/5636050/57610528-43289c80-7571-11e9-9135-407e5a7bdea7.gif)
(Popper escapes along with reference), but with the positioning you get when disabling `escapeWithReference`, i.e. without the cut-off popper:
![image](https://user-images.githubusercontent.com/5636050/57610586-63585b80-7571-11e9-8127-159b687bde86.png)

Is there a workaround for this?

**Comment by FezVrasta** [comment]
I think the codepen is not correct, I don't see the same situation as your GIFs show.

**Comment by diondiondion** [comment]
Indeed, sorry, copied the wrong URL, here's the correct one: https://codepen.io/anon/pen/WBGpqV

**Comment by FezVrasta** [comment]
Yes I fear there's no way to define on which axis enable the preventOverflow, I think we already have an issue opened to track this feature request but I can't find it at the moment

**Comment by diondiondion** [comment]
I see. For now I'll make to without the "escapeWithReference" behaviour.

> I fear there's no way to define on which axis enable the preventOverflow, I think we already have an issue opened to track this feature request

Just in case it helps define the scope of this: I suppose my request wouldn't be so much to be able to manually/statically define on which axis to prevent overflow. I'd _only_ want to disable overflow in the case when the reference element has been scrolled out of view, and it should only be disabled in that single direction.

**Comment by majdkhasib** [comment]
Hi @FezVrasta ,
If this is a breaking change, how can I fix in popper1? maybe a workaround

When viewport is small, and the content of popper is larger than viewport it gets outside of the screen

I am using this option
:
  preventOverflow: {
          padding: 0,
          escapeWithReference: true,
        },

**Comment by majdkhasib** [comment]
Note, if popper is positioned top, it should escape
but for the left and right, It should flip I guess?

**Comment by FezVrasta** [comment]
This has been fixed in more recent Popper and Floating UI versions.
