### ISSUE TITLE
Looking for new logo

### ISSUE THREAD

**Issue by FezVrasta** [popperjs/popper.js#377]
Hey guys, I'm trying to get a new logo for the project because the one I created sucks.

The idea is to have something clean and minimal, but not typography-based logos.

- Ideas?
- Anyone able and interested to design one?

I'd like to use the logo to print some stickers and maybe, in future, t-shirts?

Thanks!

**Comment by xtuc** [comment]
Popper makes me think about popcorns and it illustrates the dropdown which pops. It's just an idea.

**Comment by FezVrasta** [comment]
@xtuc cool! We just need to make it clear the lib has nothing to do with movies 🤔

**Comment by edcarroll** [comment]
@FezVrasta perhaps something involving a ruler? Since it's a positioning engine

**Comment by FezVrasta** [comment]
- popcorn
- ruler

mix together? 😁

**Comment by edcarroll** [comment]
That would be quite an interesting logo 😛

**Comment by FezVrasta** [comment]
It sucks, but I was thinking of something like this maybe.. 

![image](https://user-images.githubusercontent.com/5382443/29279292-a8da67de-8117-11e7-952c-ae3a37435b89.png)

I'm really not good with this stuff ahah

**Comment by edcarroll** [comment]
I actually really quite like that... though definitely make the popcorn more yellow (as otherwise it looks like a cloud). Not sure what that will do to the contrast with the ruler though

**Comment by aristidesfl** [comment]
Skip, just keep the popcorn

**Comment by FezVrasta** [comment]
I recently drawn this, maybe without the grave to make it less sad :-P

![image](https://user-images.githubusercontent.com/5382443/32219647-350dfe56-be2f-11e7-9f68-0eabb8b6248d.png)

**Comment by SaraVieira** [comment]
Small idea I made quickly:
![group 3](https://user-images.githubusercontent.com/1051509/32550005-695251c6-c483-11e7-89bc-88d3fa1b8795.png)

**Comment by FezVrasta** [comment]
@SaraViera that's a cool idea! I'd love it to better describe the main usage of the library (tooltips/popovers) and that's something that your current sketch lacks, but it's very funny and original!

**Comment by rmanenti** [comment]
Hey Federico,

   Here's a quick sketch of an idea.

![popper](https://user-images.githubusercontent.com/8531754/32550836-b2cd22da-c475-11e7-8e37-67fa67a5ae94.jpg)

**Comment by SaraVieira** [comment]
Do you think that changing the thing from toasts to a tooltip with the name would help?

**Comment by FezVrasta** [comment]
Probably! Maybe an hybrid? 🤯

**Comment by SaraVieira** [comment]
![group 2](https://user-images.githubusercontent.com/1051509/32552281-5261d13c-c48b-11e7-9ae4-dcec8b32475f.png)

**Comment by SaraVieira** [comment]
![group 2 1](https://user-images.githubusercontent.com/1051509/32552328-85fe9eee-c48b-11e7-9984-e2d82a003677.png)

**Comment by FezVrasta** [comment]
Now is a bit sad ☹️ (sorry!)

I liked the face on the bread slice

**Comment by SaraVieira** [comment]
OHHH

2M

**Comment by xtuc** [comment]
What about just the tooltip?

**Comment by SaraVieira** [comment]
![group 5](https://user-images.githubusercontent.com/1051509/32552714-c497ae7e-c48c-11e7-93a3-9d609ee9c247.png)

**Comment by SaraVieira** [comment]
@xtuc @FezVrasta How do you feel about
![group 6](https://user-images.githubusercontent.com/1051509/32552798-ffe1e148-c48c-11e7-8960-b922b3a86688.png)

**Comment by xtuc** [comment]
It looks amazing!

I just wondering why do you have a tooltip spawning out of a toaster :thinking: :smile:

**Comment by SaraVieira** [comment]
![tooltip _ 1 line 1 1](https://user-images.githubusercontent.com/1051509/32552907-4c2b4300-c48d-11e7-96a1-3341233eae95.png)

**Comment by FezVrasta** [comment]
So, the idea is cool in my opinion, it just needs to be realized/concretized/drawn in a more "professional" (?) way. Not sure you get what I mean.

**Comment by SaraVieira** [comment]
![tooltip _ 1 line 1 1 1](https://user-images.githubusercontent.com/1051509/32553016-99f8eac4-c48d-11e7-9bff-676801ed4c92.png)

**Comment by souporserious** [comment]
Had a little time this morning to try and get something. Figured we could riff off of tooltips :)

![image](https://user-images.githubusercontent.com/2762082/32553011-860389a4-c44a-11e7-8a65-dac1181d5bd3.png)

![image](https://user-images.githubusercontent.com/2762082/32553037-9945ada8-c44a-11e7-93c9-16f5408ea051.png)

**Comment by xtuc** [comment]
This https://github.com/FezVrasta/popper.js/issues/377#issuecomment-342826459  one :100:

**Comment by SaraVieira** [comment]
@FezVrasta I get what you mean , but I honestly don't know how to make professional stuff :(

**Comment by carolevy** [comment]
Hi :) 
Just tried this little one out... Using the colors from your website :) 
No smiley faces on toasts, sorry! 

<img width="650" alt="capture d ecran 2017-11-08 a 15 10 10" src="https://user-images.githubusercontent.com/33489027/32553348-f3ea8836-c496-11e7-92d4-e20ef384d0e6.png">

**Comment by xtuc** [comment]
@carolevy that looks amazing!

My votes goes to both:
- https://github.com/FezVrasta/popper.js/issues/377#issuecomment-342828772
- https://github.com/FezVrasta/popper.js/issues/377#issuecomment-342826459

**Comment by yuvikakoul** [comment]
Here is a suggestion for the logo. 
Have tried to have the same feel as the website and tried to keep it clean and professional.
**Thought behind the creation:**
Have connected a tooltip with the ruler to show the combination of what is provided with how it is provided. 
Cheers!
Yuvi :)
![popper](https://user-images.githubusercontent.com/9837123/32557840-4fa5d3d8-c4c9-11e7-9327-9b9ae820ee92.jpg)

**Comment by FezVrasta** [comment]
Oh damn that's actually pretty awesome!

**Comment by yuvikakoul** [comment]
Thanks  @FezVrasta  :)
Would really love to work on this with you to bring it to perfection for the project :)

**Comment by carolevy** [comment]
@yuvikakoul Hey! Really nice!! Just wondering what it would look like with a regular line instead of the dotted line around the popper?

**Comment by FezVrasta** [comment]
Can't ask more 🤩

I posted some pictures on Spectrum but I'm going to post them here as well:
![image](https://user-images.githubusercontent.com/5382443/32558842-0aa7516c-c4a6-11e7-9c9a-11831573ce37.png)
![image](https://user-images.githubusercontent.com/5382443/32558846-0dfac998-c4a6-11e7-840f-fd2dcf002024.png)

I really like the way those logos are colored, with all those gradients that creates those curves (talking particularly about the fox).

I think your logo would look great if the black and the yellow parts would be colored following the same idea. To remove the flat-iness from the logo and give it some movement.

What do you think?

**Comment by yuvikakoul** [comment]
Hey @carolevy Thanks for the suggestion. 
This is a great add and gives better sense of depth to the overall flat design.
![popper_v2](https://user-images.githubusercontent.com/9837123/32559244-b73a51ce-c4cc-11e7-86f6-9fa077c59d55.jpg)

**Comment by carolevy** [comment]
@yuvikakoul @FezVrasta Yay! Prefer this version :) great work! very professional. 
also agree with @FezVrasta  regarding the use of colour, even though I also like that they were the same as on the website!

**Comment by FezVrasta** [comment]
I think the colors may remain the same, we could just introduce some gradients using variations of them

**Comment by yuvikakoul** [comment]
@FezVrasta @carolevy how about something like this, a subtle gradient?
![popper_v3](https://user-images.githubusercontent.com/9837123/32560599-0e92cd5e-c4d0-11e7-96c0-a5a3fe58e72a.jpg)

**Comment by FezVrasta** [comment]
me like it! 😀

Just some random notes:

- is it me or the bottom left corner is sharp and the others are rounded?
- Maybe a nicer typeset for the whole logo?
- I'm not sure about the color of the border, also, do we actually need one?

**Comment by schiehll** [comment]
I'm not a designer, but I had an idea while reading the issue. Maybe you can use the negative space on the "R" to create an arrow.

Something like this, but made by someone with some design skills:

![popper](https://user-images.githubusercontent.com/5200983/32560793-aadbe1ee-c491-11e7-89ef-c4ac00ba33fe.png)

**Comment by yuvikakoul** [comment]
Hey @FezVrasta 
I've got two variations of the typeset, which I feel go with the overall theme. 
What do you suggest?
![popper_v4](https://user-images.githubusercontent.com/9837123/32561844-433b8098-c4d3-11e7-9bc3-5e6f4634de27.jpg)
![popper_v5](https://user-images.githubusercontent.com/9837123/32561845-43f1f5bc-c4d3-11e7-99ec-79ffe80dc3cf.jpg)

**Comment by FezVrasta** [comment]
I like more the second

**Comment by yuvikakoul** [comment]
Yeah, it gives an edge yet keeps it professional :)

**Comment by yuvikakoul** [comment]
Hey @FezVrasta 
Here are the icon versions of the logo. 
1 can be used for stickers, icons and the one with only can be used for small placements like favicon.
Cheers!
![popper_for-small-units-](https://user-images.githubusercontent.com/9837123/32592746-2e584094-c54b-11e7-894d-6393a82b987f.jpg)
![popper_icon](https://user-images.githubusercontent.com/9837123/32592747-2e93a012-c54b-11e7-9447-c83557dc0dc0.jpg)

**Comment by FezVrasta** [comment]
Thanks! I'm not sure about the "P.js" idea, I wonder if people will remember the name of the library if they just see that...

**Comment by yuvikakoul** [comment]
Hi @FezVrasta  
My initial choice was to use the icon with just .JS written so that it looks exactly similar to the logo that people would see on the webpage and would be able to relate to easily. 
Also, the whole idea is to slowly bring it only to the illustration without any text so that the people will recognize it just by looking at the logo :)

![popper_icon_small](https://user-images.githubusercontent.com/9837123/32646799-59fc74d0-c614-11e7-9207-27c4727e776f.jpg)

**Comment by FezVrasta** [comment]
I think we need more opinions from other people, but definitely what you have done so far is awesome. I'm not even going to compare it with the old logo because it would be an insult to your work 😂

Anyway, I still think the yellow ruler could use some love 🤔

**Comment by FezVrasta** [comment]
I tried to play a bit with the tooltip-logo idea to experiment something a little different, ideas?
<img width="800" alt="tavola disegno 1" src="https://user-images.githubusercontent.com/5382443/32698933-bc060df4-c7ad-11e7-9471-a553b5a4c28c.png">

**Comment by divyenduz** [comment]
I like the one with `.JS` the most, it fits well with the full logo (completing pooper + .js) and will give users of the site a nice recall of the logo if they see it in other places.

**Comment by yuvikakoul** [comment]
I like the usage of grid in the first one. 
Few suggestions:
the black could be toned-down a bit and add a hint of blue to match the overall theme of the website and be integrated seamlessly in the website. 
I feel .JS in the popper makes it complete (Popper.JS) and would help users understand and relate to the icon more. This way the icon can be used standalone as well.
Would like to hear your suggestions on the same, @FezVrasta . 
Cheers!
Yuvi

**Comment by FezVrasta** [comment]
@yuvikakoul I see two problems with the current design:

1. The big ".JS" in my opinion is going to look anonymous, there are thousands of libraries out there called <something>.js, I don't think that focusing on the ".js" part is going to pay.
2. I still think the ruler could use some love, I'd like it to stand out from the rest of the logo, maybe using different orientation for the shades/gradients on the yellow part?

Talking about my sketch, I like as well the grid because I think it's very meaningful. Also, something I wanted to experiment is the usage of a non-squared shape inside the existing squared one, to break a bit from the monotony of the outer shape. Maybe you have better ideas than me, but I hope my effort can help you to understand what's in my mind 😅

Thank you again!

**Comment by yuvikakoul** [comment]
Hi @FezVrasta  Something like this?
![popper_icon](https://user-images.githubusercontent.com/9837123/32848543-c76aa180-ca52-11e7-9317-b50004fd8c6c.jpg)
![popper](https://user-images.githubusercontent.com/9837123/32848547-c8bd8d40-ca52-11e7-9117-ef1d2e896be0.jpg)

**Comment by FezVrasta** [comment]
I really like how it looks, I think we should have some kind of glyph or symbol to put in the black area to make the logo unique, something subtle, maybe just of a lighter shade of gray then the rest 🤔

What do you think?

**Comment by yuvikakoul** [comment]
How about a crosshair to represent its precision and to say its right on target.
![popper_icon](https://user-images.githubusercontent.com/9837123/32850402-0a0cbcf8-ca58-11e7-804d-c6b5d2ddd740.jpg)
what do you think?

**Comment by FezVrasta** [comment]
good idea! I was thinking about something larger tho 🤔

**Comment by silvenon** [comment]
I would make the target symbol stronger and put it directly at the center, to symbolize precision. These logos are looking awesome, by the way. 🌟

**Comment by silvenon** [comment]
While @yuvikakoul's logo will be a clear winner, I wanted to play with tones a bit and this is what I came up with:

![popper](https://user-images.githubusercontent.com/471278/32984467-7336fcce-cca7-11e7-8395-73f112632174.png)

Not sure what I'm going to do with it yet, just wanted to share this draft in the meantime.

Losing the golden look would probably be a good way to proceed. 😄

**Comment by FezVrasta** [comment]
This remembers me one of the first sketches I did prepared
![tavola disegno 1](https://user-images.githubusercontent.com/5382443/32990822-72bd2db6-cd30-11e7-8fa8-74d128db9d86.png)

**Comment by FezVrasta** [comment]
Just to bring this conversation to a conclusion, @atomiks prepared one that I absolutely **love**.

![image](https://user-images.githubusercontent.com/5382443/69637814-b4392880-1059-11ea-9541-18b810fb82ca.png)

Issue resolved!
