### ISSUE TITLE
Styling Issue within the docs

### ISSUE THREAD

**Issue by IamManchanda** [popperjs/popper.js#392]
![popper-styling](https://user-images.githubusercontent.com/4970624/29410611-df84d34c-836e-11e7-8e2d-e50364c1bc13.png)

**Comment by FezVrasta** [comment]
Are you on Windows?

**Comment by IamManchanda** [comment]
Just tested in both Windows and Ubuntu!
Browser used - Chrome but I guess in other browsers too!

**Comment by IamManchanda** [comment]
Just now tested in Mac and there it works!

**Comment by FezVrasta** [comment]
I wonder if there's any way to define a custom color for the "select" button and one for the "dropdown" text... 🤔

**Comment by IamManchanda** [comment]
@FezVrasta Yes of course man 
1. https://stackoverflow.com/a/13968900/3301436
2. https://codepen.io/ralgh/pen/gpgbGx?editors=0100

**Comment by FezVrasta** [comment]
Not having Windows I can't really see any difference unfortunately 😅

**Comment by FezVrasta** [comment]
Yup this project has already automated cross-browsers test with SauceLabs actually.

I'll send a PR to fix this problem when I have some free time
