### ISSUE TITLE
attribute naming suggestion ( x-placement, x-arrow )

### ISSUE THREAD

**Issue by Aoyue-Design** [popperjs/popper.js#483]
### What went wrong?

Have you considered in accordance with the standard HTML5 to name the property?
I think the best name for "popper.js" should be `data-popper- *`

```
x-arrow -> data-popper-arrow
x-placement -> data-popper-placement
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

**Comment by FezVrasta** [comment]
Yes we should change it in a new major version.
