### ISSUE TITLE
When the popper doesn't fit in the viewport...

### ISSUE THREAD

**Issue by ConneXNL** [popperjs/popper.js#493]
It seems that when the popper doesn't fit in the viewport the popper can get on top of the target.

I got a usecase with a tooltip where I simply don't want to show the popper at all if it doesn't fit the viewport. I couldn't find any modifier that handles this usecase. Something that looks like `data-x-out-of-boundaries` added by the hide modifier (maybe `data-x-overlaps`) could really help.

As a solution I used the follow snippet:

```
                          flip: {
                              // We are using null to hide the popper if it doesn't fit anywhere
                              behavior: ['bottom', 'top', 'right', 'left', null],
                          },
```

The null makes it so that `data-placement` becomes `"null"` and I use `visible: hidden` to prevent to popper from showing.

I was wondering if I am missing something and if the use of "null" was even meant to be a thing.

**Comment by FezVrasta** [comment]
https://popper.js.org/popper-documentation.html#modifiers..hide

**Comment by ConneXNL** [comment]
@FezVrasta I am ware of data-x-out-of-boundaries. This seems to be added when target is not in the viewport. I don't think this is related to my question as `data-x-out-of-boundaries` is not added when the target is visible and the popper doesn't fit.

**Comment by FezVrasta** [comment]
Oh sorry, now it's clearer. I don't think there's anything in place to handle this situation.

I like the idea of the `null` placement, maybe we could add some tests and document it so that we make sure it keeps working when the code changes.

**Comment by ko06** [comment]
IS there any simple hack method is available for this issue?

**Comment by blackdwarf** [comment]
I am runningn into the same issue, but I would like to show the popper and have it positioned under the reference element always, regardless if the popper would fit in the viewport or not. I cannot seem to find the solution, so any help would be appreciated.

**Comment by FezVrasta** [comment]
In v2, the `hide` modifier (when enabled) will add a `data-popper-escaped` attribute when the popper is out of boundaries, and will add an additional `data-popper-reference-hidden` when the reference element is out of boundaries.

**Comment by ConneXNL** [comment]
@FezVrasta I see you closed this issue. I have not tested v2 but will the "hide" modifier also prevent the popper from overlapping the reference element? Because that was what this issue was about.

**Comment by FezVrasta** [comment]
Yes that’s not a thing anymore on v2
