### ISSUE TITLE
scrollbar size not properly computed

### ISSUE THREAD

**Issue by FezVrasta** [popperjs/popper.js#510]
https://github.com/twbs/bootstrap/issues/25013

**Comment by FezVrasta** [comment]
I think in this specific case the scrollbar appears for a microsecond and then disappears, and Popper.js caches the size of the scrollbar and doesn't update it once it disappears.

**Comment by kjdion84** [comment]
I think you're 100% correct.

**Comment by kjdion84** [comment]
I just want to mention that this issue is not present when I tried out Tooltipster. The tooltip was positioned perfectly with that package.

Perhaps look at their source code to see how they are doing calculations?

https://github.com/iamceege/tooltipster

**Comment by shepmaster** [comment]
I want to add that [@YoranBrondsema's suggestions](https://github.com/FezVrasta/popper.js/issues/457#issuecomment-367692177) worked like a charm for us! Both solutions (placing the poppers earlier in the DOM or using CSS to place it at the top) work to prevent the momentary flash of the scrollbar and the corresponding small jumps of the popper.

**Comment by kjdion84** [comment]
Adding `top: 0` to the CSS class fixed this for me.

**Comment by TyrionGraphiste** [comment]
One year later and still not fixed.

**Comment by FezVrasta** [comment]
This should be fixed in Popper 2 because we removed the broken logic all together.
