### ISSUE TITLE
Clockwise rotation does not work as expected

### ISSUE THREAD

**Issue by kyletinsley** [popperjs/popper.js#516]
### CodePen demo
https://codepen.io/anon/pen/barMXr

### What is the expected behavior?
Clockwise rotation

### What went wrong?
Does not rotate

**Comment by chriscasola** [comment]
I'm running into the same issue. I modified the pen slightly to show that even when a `boundariesElement` is provided, where the popper overlaps, it is not being moved.

https://codepen.io/anon/pen/qxBRor

**Comment by NicolasPerego** [comment]
Any idea when this bug will be solved ? It can be really problematic for responsive web apps :/

**Comment by FezVrasta** [comment]
I'm closing this as "wontfix", the plan for Popper 2 is to use a dynamic fallback value for the flip behavior, so that you don't need to rely on this kind of workarounds.
