### ISSUE TITLE
Confusing documentation with boundaries (how to ensure flip with floating navbar?)

### ISSUE THREAD

**Issue by niftylettuce** [popperjs/popper.js#518]
I have a `.navbar-fixed-top` (using Bootstrap 3 and implementing a custom Popper instance).

Trying to figure out how to make it so when you scroll down the page, a popover that begins to be hidden underneath a fixed top navbar will get flipped automatically.

I tried passing a `modifiers.flip.boundariesElement` option, but that didn't seem to work.

Is there any way to do a simple "reduce viewport top size by X pixels?" where X is the height of the floating navbar?

**Comment by FezVrasta** [comment]
You should define an offset.

**Comment by niftylettuce** [comment]
@FezVrasta how do I do that btw?  It says its an Object, but is it `offset.top`, etc?  I couldn't find it anywhere in docs and started to search in source code..

**Comment by mwebb33** [comment]
I am also confused by the offset implementation/documentation. Sorry, I tried. I got frustrated.

**Comment by mwebb33** [comment]
I basically want to set a pixel offset from the top of the viewport and the left of the viewport.

**Comment by beowulfenator** [comment]
Same problem here. @FezVrasta, can you please be more specific about there to define the offset? Thanks!

**Comment by FezVrasta** [comment]
So, the issue I was referring to is #9

**Comment by FezVrasta** [comment]
Sorry I thought Popper.js already supported it but it seems like it doesn't.

Ideally we should have an option for `preventOverflow` and `flip` that allows to set offsets on the 4 sides, it shouldn't be difficult to implement.

As workaround you may have your layout structured like this:

```
<body>
  <header />
  <main />
</body>
```

One below the other, so that you can set `main` as `boundariesElement`.

Sorry for the confusion.

**Comment by BrianBu01** [comment]
A real simple way to fix this is to change lines 72-75 in getBoundaries.js lines to:

  boundaries.left += padding.left || padding;
  boundaries.top += padding.top || padding;
  boundaries.right -= padding.right || padding;
  boundaries.bottom -= padding.bottom || padding;

I can push the changes to a branch, if you want to give me limited permissions.

**Comment by FezVrasta** [comment]
@BrianBu01 feel free to fork this repo, do you changes and send a pull request. Thanks! 🤩

**Comment by beowulfenator** [comment]
@BrianBu01 This didn't help in my case. Am I doing something wrong? How does this update work?

**Comment by BrianBu01** [comment]
For me after the change my code using Popper would be:

var popper = new Popper(
            target, 
            target.siblings()[0], {
              modifiers: {
                preventOverflow: { 
                  enabled: true,
                  boundariesElement: spacing,
                  padding: {
                    bottom: 75
                  }
                },
              }
            });

**Comment by beowulfenator** [comment]
Thank you! This solves my problem. For the default 50px tall bootstrap navbar the code looks like this:

```
var popper = new Popper(referenceElement, popperElement, {
  modifiers: {
    flip: {
      padding: {
        top: 50
      }
    }
  }
});
```

Can't wait to see your PR pulled in!

**Comment by BrianBu01** [comment]
@beowulfenator I made additional changes to that method which are pending.

**Comment by BrianBu01** [comment]
Here is a codepen just in case someone needs it.

https://codepen.io/anon/pen/RypXpV

**Comment by kasparsuvi1** [comment]
Made PR #750 for that.
@FezVrasta
