### ISSUE TITLE
Table row or cell with overflow setting breaks popup placement

### ISSUE THREAD

**Issue by donnysim** [popperjs/popper.js#526]
### CodePen demo

https://codepen.io/anon/pen/dJweJm

### Steps to reproduce the problem

1.  Have a table row or cell with any overflow, even `overflow: auto;`

### What is the expected behavior?

pop is below ref

### What went wrong?

pop is on top of ref

### Any other comments?

Breaks on all browsers so far.

**Comment by donnysim** [comment]
It's a preventOverflow modifier behavior, kind of thinking if this should really be considered as a bug?

**Comment by donnysim** [comment]
Fixing this would require something like 

```
if (/(auto|scroll)/.test(overflow + overflowY + overflowX) && element.scrollWidth > element.clientWidth) {
    return element;
}
```

but it breaks a lot of tests =.=

**Comment by FezVrasta** [comment]
Can you add a wrapper `div`? Does it work that way?

**Comment by donnysim** [comment]
No, the `getScrollParent` goes up the dom and searches for the first element that contains overflow setting, adding check if the element actually has a scroll bar actually fixes more like:

without fix:
![image](https://user-images.githubusercontent.com/8076512/35160753-c292d250-fd46-11e7-9b10-1c46dc176947.png)

with fix: 
![image](https://user-images.githubusercontent.com/8076512/35160775-dc01016c-fd46-11e7-8323-1580905affa5.png)

**Comment by donnysim** [comment]
Checking scrollHeight and scrollWidth against width and height could probably get rid of overflow computed style check.

**Comment by FezVrasta** [comment]
I think this operation may be a bit too expensive...

**Comment by donnysim** [comment]
Kind of wish there was a way to replace the `getScrollParent` with additional checks when needed. Using only scroll checks against size makes it like 2x slower, combining overflow check with scroll slows down only slightly.

**Comment by FezVrasta** [comment]
So, wait, I just re-read the function, we already read the DOM to get the overflow values, so we can add any additional check for free I think.

If you'd like to prepare a PR to improve the logic please do, just make sure to add a test to verify it actually works.

**Comment by donnysim** [comment]
That's the problem in this case, if I try adding fixes with scroll check, bunch of other tests fail and I don't really have any experience with testing js :(

**Comment by FezVrasta** [comment]
If you can prepare the PR and add the test (that pass) I can look at the other failing tests in my free time.

**Comment by FezVrasta** [comment]
This is fixed in v2
https://codepen.io/FezVrasta/pen/wvBoGpN
