### ISSUE TITLE
Wrong positioning when overflow-y:hidden is used on parent

### ISSUE THREAD

**Issue by alecpl** [popperjs/popper.js#535]
Wrong positioning on element that is inside an element with `overflow-y: hidden` or `overflow-x: hidden` (but not `overflow:hidden`).

https://codepen.io/anon/pen/WMNbxv

Result: Popper covers the reference element.
Expected: Popper on the left of the reference element.

It works in 1.12.6, but not in any newer version.

**Comment by brentertz** [comment]
@alecpl Does it work if you adjust the modifiers?

```js
modifiers: {
  preventOverflow: {
    escapeWithReference: true
  }    
}
```

https://codepen.io/brentertz/pen/RQNZNM?editors=0010

**Comment by alecpl** [comment]
Yes. It works with this modifier setting.

**Comment by alecpl** [comment]
Ok, from what I see Bootstrap 4 uses:
```
modifiers: {
  preventOverflow: {
    bundariesElement: 'scrollParent'
  }    
}
```
by default. I can fix the issue by setting the `boundariesElement` to `'window'` or `'viewport'`. And it's possible to set this via Bootatrsap's popover() `boundary` property. So, I have at least a workaround.

**Comment by FezVrasta** [comment]
I don't understand why `overflow-y` and `overflow-x` shouldn't work but `overflow` should... We do check for all of them in the `getScrollparent.js` file.

**Comment by nijk** [comment]
@alecpl You have a typo in the `boundariesElement` key in your last example

**Comment by Xotic750** [comment]
We seem to have the same or similar problem. I tried the `preventOverflow` suggestions, but no change.
<img width="1060" alt="Screenshot 2019-06-03 at 20 46 02" src="https://user-images.githubusercontent.com/216041/58826284-aa051700-8640-11e9-8c96-ee555ebc2bde.png">
<img width="1023" alt="Screenshot 2019-06-03 at 20 44 54" src="https://user-images.githubusercontent.com/216041/58826287-aec9cb00-8640-11e9-8b77-73ae8680e107.png">

**Comment by FezVrasta** [comment]
It seems fixed in v2

https://codepen.io/FezVrasta/pen/ZEYBWab
