### ISSUE TITLE
Destroy method doesn't remove all the styles

### ISSUE THREAD

**Issue by dsasko** [popperjs/popper.js#542]
### CodePen demo
https://codepen.io/dsasko/pen/LQpyyr

### Steps to reproduce the problem
1. Initiate a popper instance
2. Popper applies styles to the dropdown/tooltip/whatever
3. Destroy popper instance

### What is the expected behavior?
The destroy method should remove all applied styles.

### What went wrong?
The destroy method removes all applied styles except `will-change`.

### Other comments
This seemed like a silly thing to open up a PR for...

_/packages/popper/src/methods/destroy.js - line 18_
add: `this.popper.style.willChange = '';`

**Comment by FezVrasta** [comment]
Please feel free to send a PR
