### ISSUE TITLE
Prefer original placement if flipped placement doesn't have enough room either

### ISSUE THREAD

**Issue by atomiks** [popperjs/popper.js#550]
### CodePen demo

Default template has it
https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.  Resize the CodePen window down

### What is the expected behavior?

The popper should not flip because the flipped placement doesn't have enough room either

### What went wrong?

The popper flips

### Any other comments?

Should this be default behavior?

**Comment by FezVrasta** [comment]
yes that's something I'd like to change but it's gonna be a breaking change so we have to keep this for v2

**Comment by ipsips** [comment]
any way to work around it atm?

**Comment by FezVrasta** [comment]
You can set a custom [`flip.behavior`](https://popper.js.org/popper-documentation.html#modifiers..flip.behavior), it could be something like `['top', 'bottom', 'top']` if you want it to come back to `top` if there's not space on `bottom`

**Comment by zbrogz** [comment]
Workaround for this (I'm unable to upgrade to popper.js v2 yet). This uses the v1 API of react-popper. A similar approach can be used for popper.js v1 directly

```javascript
import { Manager, Reference, Popper } from 'react-popper';

const oppositePlacements = {
    top: 'bottom',
    bottom: 'top',
    left: 'right',
    right: 'left',
};

const Example = ({ placement }) => {
  const flipPlacement = placement.split('-')[0];
  return (
  <Manager>
    <Reference>...</Reference>
    <Popper
      placement={placement}
      modifiers={{
        ...
        flip: {
          behavior: [flipPlacement, oppositePlacements[flipPlacement], flipPlacement]
        }
      }}
    >
      ...
    </Popper>
  </Manager>
  );
};
