### ISSUE TITLE
[IE11] display:table and table-cell makes popper unable to find correct positioning

### ISSUE THREAD

**Issue by Redmega** [popperjs/popper.js#566]
### CodePen demo

https://codepen.io/Redmega/pen/WMPRGW

### Steps to reproduce the problem

1.  Use IE11
2.  Have a series of elements in a set of nested divs with `display:table` and `display:table-cell`
4.  Try to use one of the elements as a popper rel (or tooltip) (Not the top one or you can't see the issue)

### What is the expected behavior?

The tooltip should be displayed as normal (like on chrome):
<img width="314" alt="screen shot 2018-02-28 at 6 55 58 pm" src="https://user-images.githubusercontent.com/662951/36819874-2f7abb58-1cb9-11e8-9960-d1fac64ce133.png">

### What went wrong?

The tooltip cannot align itself to the top of the element properly. It goes all the way to the top of the viewport
<img width="366" alt="screen shot 2018-02-28 at 6 59 56 pm" src="https://user-images.githubusercontent.com/662951/36819970-9b5b464e-1cb9-11e8-92d7-d49eec5208b0.png">

### Any other comments?

You can see the error persist through different dependencies here (Using `react-datepicker`):
https://beautiful-crane.glitch.me/
_Note how adding position relative to the wrapper div fixes the issue on IE11._

**Comment by Redmega** [comment]
@FezVrasta If you have an idea of where to look I can try to make a PR to remedy this.

Also, what do you think of the note I added with regards to the `react-datepicker` implementation:
> Note how adding position relative to the wrapper div fixes the issue.

**Comment by FezVrasta** [comment]
I don't know honestly, I'd love to drop support for IE all together..

**Comment by Redmega** [comment]
I agree 100% but IE11 is still supported by Microsoft and widely used 😕

**Comment by jasmine-q** [comment]
I'm using [react-popper](https://github.com/FezVrasta/react-popper) and came across this issue.
What worked for me was to set `positionFixed: true` on the Popper component 
https://popper.js.org/popper-documentation.html#Popper.Defaults.positionFixed

**Comment by FezVrasta** [comment]
May someone verify if this is still an issue with `@popperjs/core@alpha`?
