### ISSUE TITLE
Add boundariesElement `scrollContent`

### ISSUE THREAD

**Issue by whitecolor** [popperjs/popper.js#572]
What do you think about adding one of the options scrollContent, so that popper will be within not scrollParent element boundaries, but within its scrollable content? To me it is quite common case.

- `scrollParent` boundaries context is the clientRect of the element that has `overflow` = `scroll`, `auto`, its sizes are `width` = `clientWidth`, `height` = `clientHeight`

- (proposed) `scrollContent` boundaries context is an the inner content of `scrollParent` so it sizes is defined by `width` = `scrollWidth`, `height` = `scrollHeight`

**Comment by FezVrasta** [comment]
I don't think I understand what you are proposing, an example would be useful.

**Comment by whitecolor** [comment]
Well say you have scroll list wrapper, which is 200px height, and scrollHeight (scroll items) actually say 1000px, `scrollParent` will limit (oveflow, flip) elment to 200px element boundares, and one may want to have popper within its scrollable content (1000px), so it maybe out of scrollParent boundaries, but within scrollable content (size of which can be determined by `scrollHeight`, `scrollWidth` props of `scrollParent`).

It is actually the quite basic case.

**Comment by whitecolor** [comment]
Actually this seems to be quite easy I just added
```js
   if (boundariesElement === 'scrollContent') {
        offsets.top -= boundariesElement.scrollTop
        offsets.left -= boundariesElement.scrollLeft
        offsets.bottom += boundariesElement.scrollHeight - boundariesElement.scrollTop
        offsets.right += boundariesElement.scrollWidth - boundariesElement.scrollLeft
        offsets.width = offsets.right - offsets.left
        offsets.height = offsets.bottom - offsets.top
    }
```

**Comment by FezVrasta** [comment]
I'm sorry I'm not understanding what you are trying to do, if you want open a new issue with a super easy to understand explanation, maybe with some example, so that I can understand this better.

**Comment by whitecolor** [comment]
Sorry I'm just not sure how to explain it better, but it is a really simple case:

- `scrollParent` boundaries context is the clientRect of the element that has `overflow` = `scroll`, `auto`, `width` = `clientWidth`, `height` = `clientHeight`

- `scrollContent` (which I propose) boundaries context is an the inner content of `scrollParent` so it sizes is defined by `width` = `scrollWidth`, `height` = `scrollHeight`

Am I still not making myself clear?

**Comment by FezVrasta** [comment]
Thanks now it's clear, I'm not sure what's the possible use case honestly. Maybe improve the first message of this issue and see if others find this useful.

**Comment by FezVrasta** [comment]
in v2 we now have the `scrollingParents` option, I think that should cover this use case.
