### ISSUE TITLE
Making popper.js XHTML-friendly

### ISSUE THREAD

**Issue by fuweichin** [popperjs/popper.js#575]
popper.js 1.12.9 doesn't support XHTML, I mean W3C-validated XHTML running in XHTML mode, yet.

To support XHTML-mode, I modified popper.js source file, replaced all `.nodeName`  with `.nodeName.toUpperCase()`, and finally my Bootstrap dropdown did work.

Any plans to add XHTML support?

**Comment by FezVrasta** [comment]
That's the first time someone asked about support for it. If enough people vote for this feature we can add it for sure.

**Comment by Artefact2** [comment]
I have the same problem when using Bootstrap dropdowns. Here is a minimal example that fails:

~~~
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" />
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" />
    </head>
    <body>
        <div class="btn-group">
            <button type="button" class="btn">Foo</button>
            <button type="button" class="btn dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" />
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Bar</a>
                <a class="dropdown-item" href="#">Baz</a>
            </div>
        </div>
    </body>
</html>
~~~

Here is the error that occurs when trying to open the dropdown:

> Error: regexp too big at popper.min.js:4:602

**Comment by Prideth** [comment]
I have a similar problem with xhtml. It does not support html in for example title attribute. Is there a way to display a tooltip with custom html and not using it with the title attribute?

**Comment by ylebhan** [comment]
I have exactly the same problem with the Bootstrap dropdowns. At least, it should be mentioned in the BS documentation. 
in XHTML, Bootstrap dropdowns work fine within a navbar, but not outside. This is quite confusing. After further readings, I found out in the BS documentation that popper.js in not used In the first case.

**Comment by atomiks** [comment]
Why are you guys using XHTML?

**Comment by ylebhan** [comment]
For me, it is just a very convenient way to ensure that my code follows strict structural and syntactic rules. And it doesn't require any additional effort.

**Comment by Artefact2** [comment]
@atomiks And why are you using HTML? Please let's not start a flame war. It boils down to personal preference, mainly due to the toolchain being different for both.

**Comment by neel5481** [comment]
I also have similar problem of dropdown with XHTML. Are we going to include in upcoming release ?

**Comment by FezVrasta** [comment]
The PR is stuck. But the "next" branch will support it

**Comment by ExE-Boss** [comment]
Since you closed #671, does that mean that you managed to get this working?

**Comment by FezVrasta** [comment]
No, I just closed some PRs that were outdated and with failing tests.

**Comment by Prideth** [comment]
In which Release will xhtml work? In our project we use JavaEE with JSF and are stuck at the moment. 
Without xhtml support we can not use popper

**Comment by FezVrasta** [comment]
@Prideth support for XML is not planned at the moment, if someone wants to send a PR to add it I'm okay with it, but the PR must be of good quality

**Comment by FezVrasta** [comment]
This is now supported in v2

**Comment by grumbaut** [comment]
The company I work for uses Popper.js for glossary definitions in its ebooks. While Popper.js works on our own proprietary ebook platform, it does not work on other online readers that display the pages as XHTML.

Would it be possible to have the solution for supporting XHTML released with a `1.x.x` tag? We're hoping to have this fix on a stable version, just so that it doesn't need to be updated across every ebook we publish.

I found that updating the following in `attachToScrollParents` resolves the issue (I believe this was mentioned above):

```javascript
var isBody = scrollParent.nodeName.toUpperCase() === 'BODY';
```

I can submit a pull request if needed.

**Comment by FezVrasta** [comment]
I’m sorry, there are several places where things should be changed to properly fix it. Unless a clean fix is provided (following what I did in v2) I don’t plan to merge PRs to fix this issue on v1.

Code stability is more important than fixing this bug at the moment.
