### ISSUE TITLE
Tip on how boundariesElement scrollParent works

### ISSUE THREAD

**Issue by lipedeitos** [popperjs/popper.js#583]
### CodePen demo

Demo 1: https://codepen.io/anon/pen/aYdbWv
Demo 2: https://codepen.io/anon/pen/JLGoQm

### Steps to reproduce the problem

1.  Demo 1 have a popper inside a modal with overflow on its content, everything works fine, the popper flips and do all the stuff.
2.   Demo 2 is using exact the same code, boundariesElement: 'scrollParent' on both, flip and preventOverflow, but in this case, the popper don't flip anymore.

### What is the expected behavior?

I know that if I change Demo 2 boundariesElement to 'viewport' instead of 'scrollParent', the popper will work like a charm, but I'm building a component with static code, and users cannot change it.
So i thought that would be nice if the property 'scrollParent' doesn't find a scrolling parent, and the body has overflow content, this property should get body/viewport/window as its boundaryElement.

### What went wrong?

Nothing actually.

### Any other comments?

Sorry about my english.

**Comment by FezVrasta** [comment]
Thanks for the suggestion, I'm not sure if it would make more sense to create a new option to change this behavior or else...

**Comment by lipedeitos** [comment]
For now i guess I'll check through pure js whats is the scrolling container and set something like `'scrollParent' || 'viewport'` on boundariesElement to work both ways without the user need use a flag/property.
If you guys have any idea of workaround while this is not enhanced I apreciate.

**Comment by whitecolor** [comment]
Maybe there refers to my recent proposal https://github.com/FezVrasta/popper.js/issues/598
