### ISSUE TITLE
Tooltip.js doesn't properly handle blur event on mobile

### ISSUE THREAD

**Issue by grzegorztomasiak** [popperjs/popper.js#592]
### CodePen demo

No CodePen needed, since it does not work even on the homepage of tooltip.js
https://popper.js.org/tooltip-examples.html

### Steps to reproduce the problem

1.  Open the given homepage on iPhone and scroll to see "It just works Hover me to see 4 tooltips!" text
2.  Touch this text and observe nothing

### What is the expected behavior?

I expect that all 4 tooltips will show up (it works on Android, Windows Mobile and everywhere I could test except iPhone)

### What went wrong?

Tooltip does not show up.

### Any other comments?

Tested on iOS 6 with Safari, Chrome and Firefox and nothing.
It does work only when element is `<a>`

**Comment by atomiks** [comment]
On iOS, the element needs to be focusable or clickable to trigger any mouse events. 

So you'd need to add `tabindex="0"` / or make it a button (which should be done for tabbing/accessibility), or give it `cursor: pointer`. A quick hack is to apply `cursor: pointer` on the body element so that touching anywhere will fire mouse events, which makes it behave like Android.

**Comment by grzegorztomasiak** [comment]
`tabindex = "0"` did the trick and it Tooltip does show up, however I have a problem to actually close it now. Normally clicking outside of the element, tooltip should dissapear but it does not on iPhone. Any ideas @atomiks ?

**Comment by FezVrasta** [comment]
Are you using Tooltip.js or Popper.js directly?

**Comment by grzegorztomasiak** [comment]
@FezVrasta, yes, like this:
```js

let tooltip = new Tooltip(myElement, {
            title: myTitle,
            html: true,
            placement: myPlacement
            offset: '0,10,0,0'
        });

        element.tabIndex = 0;
```

**Comment by atomiks** [comment]
@grzegorztomasiak as I said you need to add `cursor: pointer` to the body, which allows mouse events to occur anywhere on the page.

```js
// A common test for detecting iOS
// You can also wrap this in `document.addEventListener('touchstart')` for futher confirmation
if (/iPhone|iPad|iPod/.test(navigator.platform) && !window.MSStream) {
  document.body.style.cursor = 'pointer'
}
```

**Comment by grzegorztomasiak** [comment]
@atomiks, I have tested that previously and it does unexpected behavior on the entire app, like blinking the whole body when you touch the screen so i cannot afford have those quirks on all mobile devices including iPhone.

**Comment by atomiks** [comment]
Have you tried making [`-webkit-tap-highlight-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color) transparent?

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
