### ISSUE TITLE
Multiple oveflow/flip contexts (in order)

### ISSUE THREAD

**Issue by whitecolor** [popperjs/popper.js#598]
It would be useful for some more flexible layout scenarios:
```
        preventOverflow: {
          boundariesElement: ['scrollParent', 'viewport']
        },
```

So first it will try to fit into `scrollParent` if it doesn't fit correctly, then try `viewport`. What do you think?

**Comment by FezVrasta** [comment]
Ouch that's going to be complex I think... If enough people express their interest in this we may add it.

**Comment by matt-d-rat** [comment]
@FezVrasta Damn I ran into needing this feature today.

`Array` syntax is fine, or alternatively an object syntax might reduce some confusion:

```js
preventOverflow: {
  boundariesElement: {
    x: 'viewport',
    y: 'scrollParent'
  }
}
```

Any chance this feature could be added?

**Comment by FezVrasta** [comment]
Popper 2 supports `area` and `rootArea` options, you can set `area` to `clippingParents` and `rootArea` to `viewport`.
