### ISSUE TITLE
preventOverflow with default boundariesElement does not work properly in IE10

### ISSUE THREAD

**Issue by bimbiltu** [popperjs/popper.js#614]
### CodePen demo

https://codepen.io/anon/pen/QmPKWp

### Steps to reproduce the problem

1.  Scroll the sample

### What is the expected behavior?

The popper should stay next to the reference (as its still within the boundariesElement) and no longer be visible

### What went wrong?

In IE10 the popper will reposition so that it stays visible. In other browsers the popper will stay next to the reference as expected

### Any other comments?

This is not something I need fixed any time soon, just something I noticed while working on #585

**Comment by FezVrasta** [comment]
I'm closing this issue since it's very old and we are close to release Popper 2, which aims to support more recent browsers.

I haven't any way to test IE10 at the moment, users reported IE11 and Edge work fine though.
