### ISSUE TITLE
Body with margin and relative position causes offset placement of popper

### ISSUE THREAD

**Issue by NilsEnevoldsen** [popperjs/popper.js#618]
### CodePen demo

https://codepen.io/anon/pen/gzbaba

### What is the expected behavior?

Popper is adjacent to target.

### What went wrong?

Popper is offset from target.

### Any other comments?

Originally reported as https://github.com/atomiks/tippyjs/issues/231#issuecomment-382605125.

**Comment by loftyduck** [comment]
I found a potential workaround to add another relatively positioned element container; see https://codepen.io/lofty/pen/OZXdmW

**Comment by NilsEnevoldsen** [comment]
Thanks for the workaround. I've tried to adapt it to my use case (briefly: reusing one popper for many targets), but I can't quite get there. Everywhere I move it breaks positioning in a different way!

**Comment by NilsEnevoldsen** [comment]
Here is my (gross) workaround: https://codepen.io/anon/pen/ZqKXxq.

**Comment by FezVrasta** [comment]
🎉 cool, the new positioning algorithm is paying off.

I hope to be able to ship a stable release in the next 2 months if not sooner.
