### ISSUE TITLE
Misplacement when popper element is in a positioned element

### ISSUE THREAD

**Issue by MidnightPolaris** [popperjs/popper.js#628]
### CodePen demo

https://codepen.io/anon/pen/odyjKX

### Steps to reproduce the problem

1. Use a popper element inside a positioned container
2. The container must be different from the common offset parent (`<html>` in CodePen demo) of reference and popper
3. Set `positionFixed` to `false` (which is the default)

### What is the expected behavior?

Popper placed under reference

### What went wrong?

Popper is offset from its expected position by the same amount as the offset between positioned container and common offset parent

### Any other comments?

I did some code digging. The bug exists because:

1. In `update.js`, `data.offsets.reference` is calculated from the common offset parent.
2. In `update.js`, `data.offsets.popper` is calculated from the `data.offsets.reference`, which means the former is also relative to the common offset parent.
3. `data.offsets.popper` is used to compute styles, so they are relative to the common offset parent. But the popper is `position: absolute`, so the popper is rendered relative to its own offset parent, causing the discrepancy.

**Comment by mycarrysun** [comment]
I am having the same problem! Thanks for creating the Codepen. I am going to make a PR to try and correct this.

**Comment by raquo** [comment]
@FezVrasta Any plans to fix this bug?

Using position:relative on a common parent element that contains just the target and the popper element is the only way to keep them together when the position of the reference changes due to DOM. Manually triggering popper recalculation every time DOM changes somewhere else in the app is not a solution for any sizeable app.

**Comment by FezVrasta** [comment]
@raquo do you have a way to test with popper.j@next?

**Comment by raquo** [comment]
@FezVrasta popper.js@next has the same problem: https://codepen.io/anon/pen/MLLJGr (this codepen uses the `@next` version of popper)

**Comment by FezVrasta** [comment]
Thanks for testing, I see what's going on. I'm going to add support for this case on the `next` branch as soon I figure out how :-)

**Comment by raquo** [comment]
Thanks! I don't know how much the `next` codebase is different from v1, but if the fix ends up being easy to backport, it would be really good to have this in v1.

**Comment by FezVrasta** [comment]
`next` is a complete rewrite, the code is easier to manage, I'm not working anymore on v1 because of the complexity of the codebase.

**Comment by FezVrasta** [comment]
This is still broken on v2
https://codepen.io/FezVrasta/pen/yLyVOpy
