### ISSUE TITLE
Offset modifier function gets alternating flipped, placement and offset values when popper is flipped

### ISSUE THREAD

**Issue by enekesabel** [popperjs/popper.js#637]
### CodePen demo

https://codepen.io/enekesabel/pen/LrbgWp

### Steps to reproduce the problem

1.  Open the dev console to check logs
2.  Scroll up to make the popper flip
3.  Keep scrolling up to log more data

### What is the expected behavior?

The popper's placement is bottom, so when the itis on the top (flipped) I'd expect the following values to be logged constantly:

- flipped: true
- placement: top
- offset: 300

### What went wrong?

When the popper is flipped, the modifier gets the following values on following updates:

**First time:**
- flipped: false
- placement: bottom
- offset: 500

**Second time**
- flipped: true
- placement: top
- offset: 300

**Comment by FezVrasta** [comment]
Your custom modifier is running before the `flip` modifier, that's why you see this behavior. You can change that by defining the `order` property to a value higher than the one assigned to `flip`.

Sorry for the 1 year delay 🤦‍♂️
