### ISSUE TITLE
set arrow `position` CSS property

### ISSUE THREAD

**Issue by giladgray** [popperjs/popper.js#640]
### CodePen demo

https://codesandbox.io/s/nrypzn1yyp

### Steps to reproduce the problem

1. Go to the codesandbox link
1. See that the popper is not align correctly (note the alignment)
1. Remove the arrow element
1. See that the popper now aligns correctly

### What is the expected behavior?

For the popper to align properly to the reference element with the correct alignment even if you use an arrow.

### What went wrong?

The popper does not align correctly.

### How to fix?

@FezVrasta [says:](https://github.com/FezVrasta/react-popper/issues/165#issuecomment-386644496)

> Hey, you need to give `position: absolute` to the arrow element to have it to work properly.
>
>I wonder if it may make sense to automatically set it together with the offsets 🤔

### Versions

- Popper.js: ^1.14.1
- react-popper: 1.0.0-beta.6

**Comment by Misioka** [comment]
You should use Popper children like ```<React.Fragment>
          <div
            ref={ref}
            style={{ ...popperStyle, ...style }}
            data-placement={placement}
          >
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem,
            incidunt dicta! Molestiae harum repellendus eligendi recusandae
            labore repellat necessitatibus ipsum omnis aliquid molestias!
            Cupiditate?
            {/* Remove the arrow to make the popper alignment work as expected with the right placement */}
          </div>
          <div ref={arrowProps.ref} style={arrowProps.style} />
        </React.Fragment>```
