### ISSUE TITLE
Shouldn't close popper when focusing on popper content

### ISSUE THREAD

**Issue by balajiram** [popperjs/popper.js#645]
I have looked for the feature to mimic the following behavior, Popper shouldn't close when focusing on popper content. 
 Use case:  when the popper content has the link `<a>`. it should not be closed when its hover on itself. so the user can click the link to navigate

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
