### ISSUE TITLE
Tooltip closes unexpectedly

### ISSUE THREAD

**Issue by thanass** [popperjs/popper.js#669]
### CodePen demo

https://codepen.io/thanassis/pen/oqQEvq

### Steps to reproduce the problem

1.  Pass the mouse pointer from the right corner through the text "Hover me".
2.  You see the tooltip to be appeared. ( I add delay for close 500ms).
3.  Then move the mouse from the text to the tooltip. The problem is that tooltip closes and user can click the link.

### What is the expected behavior?

If you do the same steps as above without the first step, but start move the mouse pointer from the icon, the tooltip will not close.
What I expect is when a user catch the tooltip with the mouse pointer, this should not close.

### What went wrong?

Tooltip always close when the user moves the mouse pointer over the text "Hover me" and to the tooltip.

### Any other comments?

As you can see in the structure span is a child of the element that the tooltip was set.
I think there is a conflict between the child and the parent element.
Tooltip wouldn't close if user finally catch it with the mouse pointer.

**Comment by FezVrasta** [comment]
Thanks for the report, it looks like we don't cancel the scheduled "close" event once the mouse enters again on the tooltip

**Comment by thanass** [comment]
Thanks for your reply. How can I solve this for a project in production?

**Comment by FezVrasta** [comment]
Something like this is a possible workaround:
https://codepen.io/anon/pen/xJvLOY?editors=0110

basically, the actual tooltip element is going to be a transparent element, and inside it you position the arrow and the actual element. Doing so the mouse never goes outside the tooltip area while it moves from the button to the tooltip.

**Comment by thanass** [comment]
I appreciate your work!
This helped me to understand must better this library.
If you also apply a fix for the bug, it will be more stable for the final user.

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
