### ISSUE TITLE
Popper shows up at the wrong location for a [position:fixed, scrollable] reference element

### ISSUE THREAD

**Issue by mirraj2** [popperjs/popper.js#670]
### CodePen demo

https://codepen.io/anon/pen/VBoXgX

### Steps to reproduce the problem

1.  Position the ref element so that it is inside of a scrollable, fixed positioned container
2. Set placement to "top"

### What is the expected behavior?

I expect that the popup shows ABOVE the reference element, because I put `{placement: "top"}`

### What went wrong?

Instead, the popup displays right over the reference element instead of the space above it.

### Any other comments?

This was originally a bug that I filed with Tippy, but upon further investigation, it is a bug with Popper.  You can find the Tippy Issue here:  https://github.com/atomiks/tippyjs/issues/228

Note that the codepen linked above does NOT use the Tippy library. It only uses Popper.

**Comment by jmperro** [comment]
Same here

**Comment by ednjv** [comment]
Same problem here

**Comment by peda** [comment]
I'm having the same issue

**Comment by jinhucheung** [comment]
Same problem here

**Comment by FezVrasta** [comment]
Hey guys, I got it :-) I have already labelled the issue, if anyone wants to work on that please feel free to submit a PR with the fix.

**Comment by broyde** [comment]
@mirraj2 Seems I've found the solution.
Try
```
  modifiers: {
    preventOverflow: {
      escapeWithReference: true
    }
  }
```

**Comment by lionpeloux** [comment]
Same problem here. Is this the right fix ?

**Comment by johnknoop** [comment]
@lionpeloux 

escapeWithReference for sure does something, but it doesn't solve the problem for me.

**Comment by anhhtz** [comment]
> @mirraj2 Seems I've found the solution.
> Try
> 
> ```
>   modifiers: {
>     preventOverflow: {
>       escapeWithReference: true
>     }
>   }
> ```

Sorry, but where to put the code above ? :o

**Comment by broyde** [comment]
@anhhtz 
> Sorry, but where to put the code above ? :o

In Popper's `options`. [See documentation](https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#new-popperreference-popper-options)

**Comment by FezVrasta** [comment]
It seems fixed in v2

https://codepen.io/FezVrasta/pen/eYmBZGJ
