### ISSUE TITLE
Modifier preventOverflow causes overflow if popper is wider than viewport and preventOverflow.padding is not 0

### ISSUE THREAD

**Issue by niklaushug** [popperjs/popper.js#673]
### CodePen demo

This CodePen shows the bug and a possible workaround.

https://codepen.io/niklaushug/pen/GXJPqE

### Steps to reproduce and fix the problem

1.  Load CodePen. --> Popper flows out of viewport on the right side.
2. Enable CSS "max-width: calc(100vw - 100px);".  --> Popper does not flow anymore out of viewport.

### What is the expected behavior?

If preventOverflow.padding is greater than 0 poppers width must be limited. 

### What went wrong?

CSS property transform push element out of viewport.

### Possible solutions?

1. Add "max-width: calc(100vw - ?px);". Px value is double of preventOverflow.padding
2. Popper width must be reduced if popper width is greater than viewport width minus preventOverflow.padding width.

**Comment by FezVrasta** [comment]
This is still broken in v2 (even worse, the workaround doesn't work)

https://codepen.io/FezVrasta/pen/LYEbxrM

**Comment by atomiks** [comment]
Our `tether` option in preventOverflow is causing  these problems - mainly `center` and `surfaces`. `edges` and false work properly.

**Comment by FezVrasta** [comment]
Fixed with alpha 2

https://codepen.io/FezVrasta/pen/LYEbxrM

**Comment by jhnns** [comment]
@FezVrasta I think there was a regression. I'm experiencing this issue with the latest `2.11.0`: https://codepen.io/jhnns/pen/ZEXWLmj

**Comment by FezVrasta** [comment]
@jhnns mind to open a new issue and use the issue template please?
