### ISSUE TITLE
Support for ShadowDOM and transforms

### ISSUE THREAD

**Issue by trusktr** [popperjs/popper.js#686]
I'm using Tippy, and find it doesn't work with shadow roots or inside transformed elements (two main web techs that I use).

See the codepens in these issues:

- https://github.com/atomiks/tippyjs/issues/299
- https://github.com/atomiks/tippyjs/issues/298

Any ideas if the problem is in Tippy, or in Popper?

**Comment by trusktr** [comment]
Here's an idea to solve the transformed-container issue. We need to do something along the lines of the following (assuming the element that has the tooltip fixed onto it is itself not transformed):

- Find the [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#Identifying_the_containing_block) of the element on which we're fixing the tooltip to, as if said element has `position: absolute` (even if it doesn't have absolute position).
  - Note it doesn't list the fact there that any CSS transformed element establishes a new containing block.
- Append the tooltip to this containing block.
- Give the tooltip `position: absolute` so that it will be positioned relative to the containing block we found.
- If we're moving the tooltip based on mouse position, we need to map from screen space to the coordinate space of the containing block (how to do this is not described here)
- If we're placing the tooltip based on the target element's position, we need to find its position relative to that containing block
  - If the target element is itself not transformed, this should be a matter of traversing upward until we reach the containing block, adding up the top/left/padding/margin values along the say.

That's roughly the idea (maybe not completely correct), but paints the general direction. It may be a matter of perusing these [search results](https://www.google.com/search?num=100&ei=SEOjW9GpEobQsAWD-Y2ABw&q=screen+space+to+local+space) then figuring which DOM APIs to use.

[`react-lightweight-tooltip`](https://mcumpl.github.io/react-lightweight-tooltip/) does a super simple technique of wrapping the target element in a `position: relative` container (making a containing block) then adding the tooltip to there. It works with transforms on the container of the demo. However it has many downsides like it will break absolutely position target elements, and won't work with SVG elements, and more.

**Comment by FezVrasta** [comment]
Hi, please may you provide a codesandbox/codepen example?

**Comment by tylercrocker** [comment]
So we use shadowRoot VERY heavily with our internal CMS, and ran into this issue. I was able to resolve the tooltips not disappearing properly on mouseout/mouseleave when in a shadowRoot by just binding a custom event listener for it and calling the hide function, like so:

```js
let tip = new Tooltip(tipElement);
tipEl.addEventListener('mouseleave', (_event) => {
  tip.hide();
});
```

I used `mouseleave`, but I think that or `mouseout` both work totally fine depending on your use-case. (Refer to https://developer.mozilla.org/en-US/docs/Web/Events to make your decision there).

I'm not sure why this doesn't just work out-of-the-box, but the fix seems fairly simple. Does anyone see any reason why this might cause some sort of performance hit or anything?

**Comment by tylercrocker** [comment]
OK, here am providing examples of tooltip.js not working in ShadowDOM. Note that I also pointed out it appears to not work properly in iFrames as well, so you may wish to take what I have here and dump it into a raw test page.

https://codepen.io/cardtable/pen/GeYxyY

@FezVrasta any thoughts?

I'm fine with writing my own workarounds for ShadowDOM, but I need a way of dealing with it going out of bounds, which I haven't been able to figure out yet.

**Comment by tylercrocker** [comment]
So I WAS able to fix this by setting the `boundariesElement` to the top-most element that is NOT the body. It cannot be set to `window`, `document` or the body itself, not sure why.

```
let be = this;
while (be.nodeName !== 'BODY') {
  be = be.parentElement;
}
```

This loop that I use in all of my custom elements gets me to the proper place!

**Comment by balajiram** [comment]
positioning also doesn't work properly, when using shadowDOM.the root cause here is `document.querySelector(options.container)` doesn't find anything if container is inside shadow-root. So can we provide the one more api(configurable option) to expilicitly priovide HTMLElement for the container element similarly like `arrowElement` and `boundariesElement`. 

> options.containerElement -> HTMLElement,

**Comment by miguelyoobic95** [comment]
Are there any updates on this ? Happy to help look into an implementation that fixes the issue for all - ShadowDOM is starting to be used by a lot of people and would be a great addition to this library :)

**Comment by cihad** [comment]
> positioning also doesn't work properly, when using shadowDOM.the root cause here is `document.querySelector(options.container)` doesn't find anything if container is inside shadow-root. So can we provide the one more api(configurable option) to expilicitly priovide HTMLElement for the container element similarly like `arrowElement` and `boundariesElement`.
> 
> > options.containerElement -> HTMLElement,

@balajiram you can give dom object to options.container

**Comment by FezVrasta** [comment]
As of today, positioning seems to work in both the codepens provided [here](https://github.com/popperjs/popper.js/issues/686#issuecomment-423044114).

Tooltip.js is deprecated, so the mouseleave issue is irrelevant.
