### ISSUE TITLE
Focus tooltips don't show when manually triggerring focus on blur

### ISSUE THREAD

**Issue by alexturpin** [popperjs/popper.js#687]
In our app, if a user tabs out of a field where there is a validation error, we focus back on the field (only once) to show them the error in a focus tooltip. I've been porting our tooltip library to Tooltip.js and noticed that if have a field with a tooltip that should trigger on `focus` and you try to manually trigger focus on that field during the `blur` event, the tooltip doesn't show.

Here is a demo: http://jsfiddle.net/fkat7m4p/

The cause of this is that even when there is no `delay` configured, `setTimeout` is used to trigger `_show` and `_hide`. It essentially means that the manual focus is two ticks early. One can work around with two `setTimeout` set to `0` as shown here: http://jsfiddle.net/k2onwrxd/

I would be happy to submit a PR that doesn't use `setTimeout` when the delay is 0, but I'd just like to check before if this is something that would be accepted / that you would be interested in.

**Comment by alexturpin** [comment]
Another consequence of using `setTimeout` in such cases is that if the tooltip text is changed on blur, there can be a flash of the new text before the tooltip is properly hidden on the next tick.

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
