### ISSUE TITLE
closeOnClickOutside don't work after tooltip show() method.

### ISSUE THREAD

**Issue by lotr1903** [popperjs/popper.js#688]
### CodePen demo

https://codepen.io/anon/pen/ZMPJQb

### Steps to reproduce the problem

1.  Open the demo.
2.  Click the button "Click me"
3.  Tooltip will show itself.
4. Try to click outside the tooltip.
5. Tooltip wont close.
6. If you click on "Tooltip", it works correctly.

### What is the expected behavior?

I expect when trigger show from button and appear on the page, Tooltip close when I click outside.

### Any other comments?

Is this a bug or normal behavior ? How can I make it work like default show() method ?

**Comment by jeff-nz** [comment]
Hi @lotr1903 ,

Perhaps simulating the click action might help by using `.click()` instead of calling `tooltip.show()` directly.

So your js file should look something like:
```
$(document).ready(function(){
 var elmt =  $('.icon');
  
	var tooltip = new Tooltip(elmt, {
    placement: 'bottom-end',
    title: 'Test Text',
    closeOnClickOutside: true,
    trigger: "click",
    modifiers: {
      flip: {
        behavior: ['left', 'right', 'bottom']
      },
    },
  });

  var button = $("#button");
  button.on("click", function(e) {
    elmt.click();
  });
});
```
Hope it helps.

**Comment by Wyzix33** [comment]
Not a solution for dynamic content, usualy onClick does some other operations, not just displaing the tooltip...

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
