### ISSUE TITLE
Methods to disable / enable tooltip

### ISSUE THREAD

**Issue by alexturpin** [popperjs/popper.js#691]
It's sometimes useful to temporarily disable a tooltip from triggering through user events (focus, hover, click, etc). Other libraries provide an `enable` and `disable` method to do this. Right now, the only way to do this is by calling `destroy` on the tooltip to disable it and reinitializing it to enable it.

I'm happy to provide a PR with this feature if it is deemed that it should be part of the library.

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
