### ISSUE TITLE
Dispose does not clear the show timeout

### ISSUE THREAD

**Issue by alexturpin** [popperjs/popper.js#694]
### CodePen demo

http://jsfiddle.net/z2xcd07p/1/

### Steps to reproduce the problem

1.  Quickly click on the blue rectangle to dispose the tooltip and delete the dom element before the delay has a chance to trigger

### What is the expected behavior?

Everything is cleaned up properly.

### What went wrong?

The show timeout is not cleared on dispose and so when it triggers, it causes an error.

### Any other comments?

I will make a PR to fix this once I've submitted a PR for #687 and it has been merged in.

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
