### ISSUE TITLE
flipVariations logic is reversed

### ISSUE THREAD

**Issue by ferdaber** [popperjs/popper.js#696]
### CodePen demo
https://codepen.io/igrek312/full/WaRrZO/

### Steps to reproduce the problem
1.  Create a popper instance with a defined variation position (`'start'` or `'end'`)
2.  Enable flipping the variations `{ modifiers: { flip: { flipVariations: true } } }`
3.  Verify that the variation itself does not flip when the popper overflows that boundary.

### What is the expected behavior?
The variation is flipped (`'end'` becomes `'start'` and vice versa).

### What went wrong?
The logic seems to be faulty?
https://github.com/FezVrasta/popper.js/blob/6d98b8b29aa8410be9dd99f423d94e3540019fce/packages/popper/src/modifiers/flip.js#L100
Where the boolean expression checks for `variation === 'start'`, it should be `'end'` instead, and vice-versa.

When a popper is `'bottom-start'`, for example, the popper's origin is the top-left corner, so we should be checking for overflowing on the right, instead of on the left.

### Any other comments?
`flipVariations` itself is not documented in the type definitions, nor in the API.

**Comment by ferdaber** [comment]
I can also create a PR to fix this. I'd just like some verification that the current behavior is *not* the intended behavior.

**Comment by FezVrasta** [comment]
Your demo doesn't work because the popper is inside the ref, it should be near it instead.

https://codepen.io/anon/pen/MzyaZK

But I agree the behavior doesn't seem right.
