### ISSUE TITLE
Arrow position incorrect when an inner element has a border

### ISSUE THREAD

**Issue by atomiks** [popperjs/popper.js#710]
### CodePen demo

https://codepen.io/anon/pen/dQpGdm

### Steps to reproduce the problem

I noticed this after creating a tooltip theme with a border.

![img](https://i.gyazo.com/cf9f10d83a329253aa8736573deb7763.png)

1.  Zoom right into both demos

- The top one has an inner element with the arrow inside it, and its position is incorrect (1px too far -- happens for both horiz and vertical placements).

- The bottom one has the arrow directly inside the popper, and its position is correct.

It only happens when the inner element has a `border`.

### What is the expected behavior?

Correct position of the arrow

### What went wrong?

Arrow is 1px too far (aka the `top` for horizontal placement and `left` for vertical placement is rounded? too much).

**Comment by FezVrasta** [comment]
@atomiks is this fixed in v2?

**Comment by atomiks** [comment]
Since we're using `getBoundingClientRect` probably but I'll test it to see

**Comment by atomiks** [comment]
It's fixed 👍
