### ISSUE TITLE
Incorrect tooltip location for elements with 0 height if placement: 'bottom-start'

### ISSUE THREAD

**Issue by knstnt-dev** [popperjs/popper.js#721]
### CodePen demo

https://codepen.io/anon/pen/bQqgeE

### Steps to reproduce the problem

1.  Create popper using element with 0 height as a reference and placement: 'bottom-start'.

### What is the expected behavior?

Tooltip element is located at the bottom of its reference.

### What went wrong?

Tooltip element is located at the top of the page.

### Any other comments?

This issue was found while integration of popper.js with one text editor that producing elements with 0 height sometimes. I understand that firstly it’s an issue of that editor, but also will be nice to fix it in popper too.

**Comment by FezVrasta** [comment]
Sorry, I never answered to this one.

This is expected, reference margins are not considered when positioning the popper.
