### ISSUE TITLE
Tooltips manually hidden with .hide don't show properly

### ISSUE THREAD

**Issue by alexturpin** [popperjs/popper.js#727]
### Demo

http://jsfiddle.net/kn82c3fz/

### Steps to reproduce the problem

1. Setup a tooltip with a `click` trigger
2. Click the trigger to show the tooltip
3. Hide the tooltip with `.hide()`
4. Try to open the tooltip with the click trigger

### What is the expected behavior?

The tooltip should open.

### What went wrong?

The tooltip doesn't open the first time around, but does the second time.

### Any other comments?

This is due to `.hide()` not setting `_isOpening` to `false`. I will make a PR for this soon, I just made this issue to track all the PRs I'll be making.

**Comment by FezVrasta** [comment]
Thanks for the upcoming PR!

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
