### ISSUE TITLE
Unable to determine version from minified js

### ISSUE THREAD

**Issue by fokep** [popperjs/popper.js#729]
### Steps to reproduce the problem

1. Use a minified version of popper.js with Bootstrap
2.  Let time pass
3.  Update Bootstrap and get the latest popper.js
4. Have errors showing up in console
5. Open popper.min.js
6. Look for version number

### What is the expected behavior?

Being able to determine software version from source and understanding changes by browsing the changelog

### What went wrong?

`popper.min.js:4 Uncaught SyntaxError: Unexpected token export`

Had a hard time finding the version number and determining starting point in changelog

### Any other comments?

Since the minified file doesn't contain version number, it is time consuming to identify the version

### Suggested improvement

Add version number to minified files

**Comment by DanielRuf** [comment]
This would be very helpful, for example as property on a Popper instance like jQuery does it with `jQuery.fn.jquery`.
