### ISSUE TITLE
Auto placement available space calculation

### ISSUE THREAD

**Issue by petermonte** [popperjs/popper.js#734]
### CodePen demo
https://codepen.io/anon/pen/ebEjXj

### Steps to reproduce the "problem"
scroll up and down until the element that receives the tooltip (black square) reaches top or bottom of Codepen preview container.
![tooltip](https://user-images.githubusercontent.com/4997381/50488249-7b33a680-09f9-11e9-9cd9-cae30b64fd4e.gif)

### What is the expected behavior?
To have the tooltip changing the auto placement only when the calculation cannot fit the element based on size plus offset.
![screenshot-2018-12-27-at-17 06 48](https://user-images.githubusercontent.com/4997381/50488548-f2b60580-09fa-11e9-8259-88863faff41b.png)

### What went wrong?
The change of the placement is done earlier than expected as if calculating the center of the container as the switch moment.
![screenshot-2018-12-27-at-17 06 48](https://user-images.githubusercontent.com/4997381/50488607-47f21700-09fb-11e9-8900-f710cdbc7b91.png)

### Any other comments?
This issue not being raised as a bug but rather a question.

**Comment by FezVrasta** [comment]
Unfortunately I think this is the expected behavior right now, the `auto` placement will always position to the side with more available space. I think to "fix" this we should calculate the available space only at the beginning and not un subsequent updates.

**Comment by petermonte** [comment]
@FezVrasta thanks for the feedback and thanks for such library. Your code is being used on a UI kit I'm building and it is amazing how many components require **popper.js** logic.  

For better context, please bear in mind that I am focusing **Tooltip.js** and not **Popper.js**.

It would certainly be nice to have this behavior. In some contexts it is desired to leave the tooltip always at top, as much as possible, in favor of leaving the bottom side readable. Take for example a sequence of table rows each with a tooltip. If you start hovering from top to bottom (default behavior) you would expect to have the following rows visible and not hidden by the tooltip.
With this what I mean is: Once I define a specific placement combined with `auto *` the desired position will always be the side and not the `auto`. I think `auto` comes as an exception to adapt to the user interaction. So the behavior would be to keep the requested position as much as possible, and if not possible to comply any more then, yes,  apply the auto positioning.

**Comment by FezVrasta** [comment]
I agree there are better default behaviors for "auto".

If you have time you may open a PR targeting the "next" branch where you add a text file that describes what a good "auto" behavior could be. Trying to be as technical as possible to help me with the conversion to code

**Comment by petermonte** [comment]
It's a deal. Thanks.

**Comment by hyvyys** [comment]
Any updates on this? I think this issue affects a lot of frameworks that use Popper. Example:
https://recordit.co/FJ1w2xYoFm

**Comment by petermonte** [comment]
@hyvyys 

I've been under a lot of work and have not yet found the time to draw the entire [perspective](https://github.com/FezVrasta/popper.js/issues/734#issuecomment-450209728) of how should the behavior be in terms of Tooltip.js.

**Comment by atomiks** [comment]
@hyvyys I think that is this issue: https://github.com/FezVrasta/popper.js/issues/550

**Comment by FezVrasta** [comment]
This should be addressed in `@popperjs/core@2.0.0-rc.1`
