### ISSUE TITLE
Flip modifier `behavior` doesn't work correctly

### ISSUE THREAD

**Issue by AndreyGladkov** [popperjs/popper.js#755]
### CodePen demo

https://codepen.io/andreygladkov/pen/aMvZEG

### Steps to reproduce the problem

1.  Open CodePen template

### What is the expected behavior?

Should flip to the left or right.

### What went wrong?

Flip work only --start or --end current placement.
In the current example, the flip should change placement to the right or left and not overlap the ref element.

### Any other comments?
I think the problem is in this code:
https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/modifiers/flip.js#L62

```
if (placement !== step || flipOrder.length === index + 1) {
      return data;
}
```

Placement is always not equals step. Is equal if --start or --end placement.

if corrected as follows:

```
if (data.placement === step || flipOrder.length === index + 1) {
      return data;
}
```

Will flip left or right.

**Comment by flaviusmatis** [comment]
I've noticed the same issue. Following.
