### ISSUE TITLE
Popper element is not positioned correctly when reference elements is in an offset iframe

### ISSUE THREAD

**Issue by maciejszpyra** [popperjs/popper.js#791]
### CodePen demo

https://codepen.io/maciejszpyra/pen/JjPRXrm

### Steps to reproduce the problem

1.  Have a reference element inside iframe
2. Iframe needs to be offset
3.  Create Popper alignment

### What is the expected behavior?

That popper element will be correctly positioned.

### What went wrong?

It appears that popper is ignoring the position of the iframe in the parent document when calculating the popper element offset.

### Any other comments?

Is there any option we can set to make this work, do we need to crate modifier to fix this or is this just a bug?

**Comment by IGreatlyDislikeJavascript** [comment]
@FezVrasta +1 for this issue, I've had this reported for Bootstrap Tourist (tour step in iframe not aligned to element), and the underlying cause is popper.js not obeying iframe offset.

I think this needs to be fixed in popper.js. Although we can manually shift the popover by getting the element in the iframe and setting an offset initially, if the content in the iframe is responsive and the layout changes then it becomes complicated to solve this outside of popper.js. 

In addition, BS4 doesn't expose all the popper options, so it's actually impossible in some scenarios (as per my reply to you in my repo).

Thanks!

**Comment by maciejszpyra** [comment]
I linked better codepen example

**Comment by cytrowski** [comment]
Have you considered using the modifiers? https://github.com/popperjs/popper.js/blob/master/docs/_includes/popper-documentation.md#modifiers--object

**Comment by FezVrasta** [comment]
May someone test this bug with @popperjs/core@next?

**Comment by cytrowski** [comment]
> May someone test this bug with @popperjs/core@next?

I can do it Today :) stay tuned

**Comment by cytrowski** [comment]
Sadly it's even worse: https://codepen.io/cytrowski/pen/MWYepgL

Right now to see the popper element you have to resize the window. With 1.16 it's at least visible.

**Comment by atomiks** [comment]
Hi @cytrowski you need to be trying the latest `@next`. I did and the bug is there, but it's positioned where the button would "originally" be if the iframe was not offset. So we need to take into account iframes' position on the document as well? 🤔

**Comment by FezVrasta** [comment]
https://codepen.io/FezVrasta/pen/dyPXvMp

**Comment by atomiks** [comment]
That doesn't work @FezVrasta 

This one works: https://codepen.io/atomiks/pen/qBENrNZ

**Comment by FezVrasta** [comment]
Thanks, so it looks like v2 is not worse, but not better, than v1

**Comment by cytrowski** [comment]
> Hi @cytrowski you need to be trying the latest `@next`. I did and the bug is there, but it's positioned where the button would "originally" be if the iframe was not offset. So we need to take into account iframes' position on the document as well? 🤔

Yes, that's the issue we experience :) Thank you for looking into that

**Comment by cytrowski** [comment]
Just a quick question @FezVrasta - are you going to fixing this in the next week or so? If not I can try doing the PR with a fix. Also I think it's worth fixing in 1.17 as well as in the latest version

**Comment by FezVrasta** [comment]
Right now I'm working in preparation of the release of Popper 2, so I doubt I'll have time to look at this issue. If you'd like to send a PR that'd be great.

I don't plan to continue the development of the 1.x branch if not for security vulnerabilities.

**Comment by atomiks** [comment]
The easiest fix for this is just to put the popper element in the same iframe context as the reference element. Having them disjoined in different documents breaks ARIA IDs, so there are accessibility concerns with doing this in the first place. It doesn't seem like this is worth it to fix/handle due to that.

**Comment by FezVrasta** [comment]
Closing as per above comment.

**Comment by cytrowski** [comment]
> The easiest fix for this is just to put the popper element in the same iframe context as the reference element. 

Sadly that's a no-go in my use case (page layout requires the popper element to be in the parent context - It has to be visible and not cropped by the iframe boundaries)

> Having them disjoined in different documents breaks ARIA IDs, so there are accessibility concerns with doing this in the first place. 

What if I'm able to guarantee the uniqueness of IDs across the whole page (including iframes)?

> It doesn't seem like this is worth it to fix/handle due to that.

As far as I know iframes can be perfectly accessible and in some cases (microfrontend) they are the only reasonable way to go. I would consider putting some effort in fixing this issue (I can work on it) https://webaim.org/techniques/frames/

**Comment by FezVrasta** [comment]
If you'd like to add support for this, consider to create a replacement for the [popperOffsets](https://popper.js.org/docs/v2/modifiers/popper-offsets/) modifier, it should be enough to make you able to add the necessary logic to handle iframes.

**Comment by atomiks** [comment]
> What if I'm able to guarantee the uniqueness of IDs across the whole page (including iframes)?

When I tested using VoiceOver, having focus on the button didn't announce the popper content with `aria-describedby`. The IDs are only referenced in the same document context :\

**Comment by cytrowski** [comment]
> > What if I'm able to guarantee the uniqueness of IDs across the whole page (including iframes)?
> 
> When I tested using VoiceOver, having focus on the button didn't announce the popper content with `aria-describedby`. The IDs are only referenced in the same document context :\

Can you share your example?

**Comment by atomiks** [comment]
In the iframe:

```html
<button aria-describedby="popper">My button</button>
```

In the main document:

```html
<div id="popper">My popper</div>
```

When inside the iframe focusing the button, `"My popper"` is not announced like it should be

**Comment by cytrowski** [comment]
https://github.com/popperjs/popper-core/issues/791#issuecomment-578678672 - I'm not sure it's a valid use case for `aria-describedby` attribute considering the fact that the dialog body may not be available on button focus - only after it's clicked.

**Comment by atomiks** [comment]
That pattern is for tooltips rather than interactive popovers. I'd guess focus management can handle interactive popovers.

**Comment by cytrowski** [comment]
https://github.com/popperjs/popper-core/issues/791#issuecomment-578681515 - in that case I believe tooltip body can live inside the iframe (won't affect layout that much). I'm focused more on interactive ones. We can mention the problem in the docs.

**Comment by luminaxster** [comment]
Sadly, I got to inject the iframe offset directly to "fix" it:
```js
const clientRect = iFrameContainer.getBoundingClientRect();
const containerOffsetTopPos = clientRect.y;
const containerOffsetLeftPos = clientRect.x;
....
modifiers={[
                                    {
                                        name: 'offset',
                                        options: {
                                            offset: [
                                                containerOffsetLeftPos,
                                                containerOffsetTopPos
                                            ],
                                        },
                                    }]}
```
iframe offsets used to work out of the box in V1 =(.

**Comment by tounsoo** [comment]
I am not really seeing any solution here? no?

**Comment by mhanley00** [comment]
> I am not really seeing any solution here? no?

This stack post was super helpful for Popper 2x, I didn't see the `update` property documented anywhere: https://stackoverflow.com/questions/65585859/react-popper-incorrect-position-on-mount

I ended up calling that `update` function onClick in React and then
- adding a hidden button also outside of the iframe, but at the same position as the iframe, basically what @luminaxster did, and with another piece of state for ref
- using the hidden button as the anchor for the popper (popper outside of iframe)

```js
  /* "ref" for real button inside iframe */
  const [realAnchor, setRealAnchor] = useState();
  /* "ref" for invisible button outside of the iframe  */
  const [fakeAnchor, setFakeAnchor] = useState();
  /* "ref" for the popper  */
  const [popperElement, setPopperElement] = useState();

  const { styles, attributes, update } = usePopper(
    fakeAnchor,
    popperElement,
    {
      name: 'popper-menu',
      phase: 'main',
      enabled: true,
      options: {
        offset: [0, 0],
      },
      requiresIfExists: ['offset'],
    },
  );
  ...
  <InvisibleAnchor
      id="popup-anchor"
      aria-hidden="true"
     // pass down top/left in CSS
      top={realAnchor?.getBoundingClientRect()?.bottom ?? 0}
      left={realAnchor?.getBoundingClientRect()?.left ?? 0}
      ref={setFakeAnchor}
      />
      <iframe>
     // other stuff in iframe
        <CoolButtonThatOpensPopper
            onClick={async () => {
            await update();
             }}
            ref={setRealAnchor}
           / >
     </iframe>
  
```
