### ISSUE TITLE
One advice about params of boundariesElement and appendToBody

### ISSUE THREAD

**Issue by superchangme** [popperjs/popper.js#799]
The popover plugin has two params: 

1.boundariesElement  : means the popver element's boundaries rely on which elment ( default is scrollParent) //**In the old verion this param is viewport** (means the window)
2.appendTobody : means the popver elment should append to body or not (default is true)

Now i want say that when we append an element  to body ,generally it means  we want the element **dont  be affected by other elements.** But in popover plugin,the popover  which is appented to body will be affected by its scrollParent .

My advice is when appendToBody is true we should set the default  boundariesElement  should be **viewport**.
That can be convenient,and it's friendly to the users  who are using old popover plugin version.

Here is my code

```js
 options.modifiers = _.merge(
        {
          preventOverflow: {
            boundariesElement: this.appendToBody === true ? 'viewport' : 'scrollParent'
          },
          applyStyle: {
            gpuAcceleration: false
          }
        },
        options.modifiers
      )

``` ```

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
