### ISSUE TITLE
Positioning not correct on iOs when keyboard is open

### ISSUE THREAD

**Issue by PedroBorracho** [popperjs/popper.js#805]
I'm using popper to render validation errors on Inputs, and I'm facing a wrong positioning when on iOs the keyboard is open:

when keyboard opens due to the focus on the Input:
* the viewport is resized
* the body scrolls automatically to the input
* popper is initialized but is not placed in the correct place. Scrolling the body, the popper position changes each time (is not following the target properly)

### CodePen demo

The scenario can be reproduced with the html included in the zip, by starting a webserver in the folder.
[popperJsIosBug.zip](https://github.com/FezVrasta/popper.js/files/3400653/popperJsIosBug.zip)

### Steps to reproduce the problem

Start a webserver and target the page with iPhone or XCode simulator

1.  scroll down to the input
2.  tap on the input to gain the focus

### What is the expected behavior?

Browser should scroll to the input, open the keyboard: the popper should be rendered on the "X"
<img width="402" alt="expected" src="https://user-images.githubusercontent.com/1810992/61356440-a6d38c80-a876-11e9-8b4b-d8744ba08458.png">

### What went wrong?

The positioning is incorrect (it might also be out of the viewport), scrolling the popper will appear.
<img width="409" alt="inital position wrong" src="https://user-images.githubusercontent.com/1810992/61356264-447a8c00-a876-11e9-94ea-a0c1c63fbba3.png">

<img width="410" alt="position changes with body scroll" src="https://user-images.githubusercontent.com/1810992/61356097-e8b00300-a875-11e9-9a0e-ecae0db5165c.png">

These are the options provided to popper:
```
{
   positionFixed: true,
   removeOnDestroy: true,
   modifiers: {
       preventOverflow: {
           boundariesElement: 'viewport'
       }
    }
 }
```

The options that seems to break the positioning is positionFixed.

**Comment by mreinstein** [comment]
@PedroBorracho you might be better off using native form validation. This is built in since ios 10.3: 

https://caniuse.com/#feat=form-validation

**Comment by FezVrasta** [comment]
This is an iOS behavior/bug ([as reported here](https://stackoverflow.com/questions/49373265/ios-safari-keyboard-appearence-does-not-trigger-window-resize-event)), a possible workaround could be to add a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to an HTML element set to `position: fixed; top: 0; left: 0; right: 0; bottom: 0;` but it's outside the scope of Popper, so it's better to do that on user land.

**Comment by moodysalem** [comment]
> This is an iOS behavior/bug ([as reported here](https://stackoverflow.com/questions/49373265/ios-safari-keyboard-appearence-does-not-trigger-window-resize-event)), a possible workaround could be to add a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to an HTML element set to `position: fixed; top: 0; left: 0; right: 0; bottom: 0;` but it's outside the scope of Popper, so it's better to do that on user land.

Why is that outside of scope? Popper handles all other viewport resize events, and that workaround sounds like it would work for any other resize events. And it’s not documented afaict how to inform popper of a new window size.

Can you share how we should go about informing popper of the new viewport size?

**Comment by Grawl** [comment]
Just faced this problem on iOS. Any possible workarounds? Maybe ready to use modifier?

**Comment by Flakelf** [comment]
@Grawl did you solve it?

**Comment by Grawl** [comment]
@Flakelf Not yet

**Comment by Grawl** [comment]
@Flakelf recently I used VisualViewport API and realized that top point of iOS virtual keyboard is `visualViewport.height` + `visualViewport.offsetTop` from JS API
