### ISSUE TITLE
offset on offset modifier is overwritten

### ISSUE THREAD

**Issue by luxferresum** [popperjs/popper.js#812]
### CodePen demo

https://codepen.io/anon/pen/eqWwPY

### Steps to reproduce the problem

1.  create a tooltip and give `popperOptions` with an `offset` modifiert with an `offset` property but no `offset`.

### What is the expected behavior?

The offset of the offset modifier should be used.

### What went wrong?

The offset of the offset modifier gets replaced by `undefined`

### Any other comments?

The problem is probably [this](https://github.com/FezVrasta/popper.js/blob/master/packages/tooltip/src/index.js#L234).

I'm not 100% sure if this is a real problem or the expected behaviour. Then its just a documentation issue.

**Comment by FezVrasta** [comment]
Thanks for the report, creating a PR to fix this should be fairly simple, would you like to give it a try?

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
