### ISSUE TITLE
allow committing on nixos

### ISSUE THREAD

**Issue by luxferresum** [popperjs/popper.js#813]
### Steps to reproduce the problem

1.  use nixos
2.  change any file
3.  run `git commit`

### What is the expected behavior?
it creates a commit

### What went wrong?
it assumes there is `/bin/bash`. This is actually a problem of the dependency [pre-commit](https://www.npmjs.com/package/pre-commit).
While it was fixed [two years ago](https://github.com/observing/pre-commit/commit/f25888ffc67d21beaa1572b53ab6704a67266b64) they haven't published a version to `npm` for 
3 years.

**Comment by FezVrasta** [comment]
What's Nixos?

**Comment by luxferresum** [comment]
[A linux distribution](https://nixos.org/).
The problem is that nixos, like some distros, does not has bash at `/bin/bash`.

[`#!/bin/bash` is *not* the correct shebang for `bash`, but `#!/usr/bin/env bash` is.](https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash/21613044)

While this is a problem of `pre-commit` that is fixed on master branch, the problem for `popper.js` is that `pre-commit` seems pretty unmaintained, considering that fix didt make it to a relase in 2 years.

**Comment by FezVrasta** [comment]
I opened an issue here https://github.com/pre-commit/pre-commit/issues/1106

**Comment by luxferresum** [comment]
Has this been fixed?

**Comment by FezVrasta** [comment]
It’s an issue with a dependency, I can’t do anything unfortunately
