### ISSUE TITLE
Tooltip.js 'closeOnClickOutside' not working on iOS

### ISSUE THREAD

**Issue by Miriam-diva-e** [popperjs/popper.js#825]
### CodePen demo

https://codepen.io/MeowMeowMeowMeow/pen/RwbLNxm

### Steps to reproduce the problem

1.  Open CodePen on iOS
2.  Click reference => the tooltip is shown
3.  Click somewhere else

### What is the expected behavior?

As ```closeOnClickOutside``` is set to true, the tooltip is supposed to be closed as soon as you click somewhere.

### What went wrong?

If ```closeOnClickOutside``` is set, Tooltip.js adds an event listener to the ```document``` that listens to ```mousedown``` events. On iOS however, this event will only be triggered if the user clicks on a clickable element, i.e. an element, that either has an event listener for click events or the CSS ```cursor: pointer```.

### Any other comments?

We want the tooltip to be closed on every click outside. Thus, transforming every element into a clickable element is not an option as we neither want the pointing cursor everywhere on desktop, nor add empty click listeners to every element in the application.  I guess the touch event needs to be handled here to account for the iOS Safari event handling.

**Comment by chidev** [comment]
There needs to be a `touchend` in addition to `mousedown` on the document. I manually added this to tooltip.js and it seems to be working.

**Comment by FezVrasta** [comment]
Hi, I'm interrupting the development of the `tooltip.js` library to focus on the development of `@popperjs/core` (Popper.js v2).

Please consider switching to [Tippy.js](https://github.com/atomiks/tippyjs), which is a way better alternative to Tooltip.js and is well maintained. Tippy.js still uses Popper.js under the hood, so you will find all your favourite features.

I'll close this issue.
