### ISSUE TITLE
Offset modifier ignores second axis based on placement

### ISSUE THREAD

**Issue by IGreatlyDislikeJavascript** [popperjs/popper.js#832]
# CodePen demo

https://codepen.io/IGreatlyDislikeJavascript/pen/bGGNgOj

### Steps to reproduce the problem

Popper won't reliably adjust X/Y positioning on both axis, only the primary axis depending on popper placement. 

1.  Simply try to adjust popper position on both axis

### What is the expected behavior?

Ability to adjust in both axis as per docs!

### What went wrong?

Popover doesn't adjust

### Any other comments?

Code is correct because one axis adjustment happens successfully. Using an offset modifier of (for example) `"100px, 200px"` will correctly adjust one axis at a time, but not both. So if the placement is to the left or right of the element, the horizontal offset of 100px will be used but the 200px vertical element ignored. 

If placement is made above or below element, the horizontal offset of 200px has no effect but the vertical offset of 100px is correctly set.

This is frustrating because, if it worked reliably, it would help solve a number of other issues/requests both for popper (e.g.: iframe element positioning) and my repo.

**Comment by IGreatlyDislikeJavascript** [comment]
@FezVrasta thanks for confirming v2 fix, will await your release.

**Comment by iamvijaydev** [comment]
I went ahead and fixed by passing a modified `anchorEl`. I hope this will be a solutions to those who are stuck with version 1:

```javascript
const getBoundingClientRect = () => {
  const ret = {};
  const source = currentTarget.getBoundingClientRect();

  for (const prop in source) {
    if (prop === 'left') {
      ret[prop] = source[prop] - 6;
    } else {
      ret[prop] = source[prop];
    }
  }

  return ret;
};

setAnchorEl({
  clientWidth: currentTarget.clientWidth,
  clientHeight: currentTarget.clientHeight,
  getBoundingClientRect
});
```

As you see the `left` value is altered from the original value. Please note that (with React) we also need to set `anchorEl` to null when not required. So do wrap the above code in something like this:

```javascript
useEffect(() => {
  if (currentTarget) {
    ...above code
  } else {
    setAnchorEl(currentTarget);
  }
}, [currentTarget]);
```
