### ISSUE TITLE
Popper doesn't flip

### ISSUE THREAD

**Issue by NemoDima** [popperjs/popper.js#835]
### CodePen demo
https://codepen.io/vovaltus/pen/rNNjONg 

### Steps to reproduce the problem
1.  Move "Drag me" popper left
2.  "Flipping popper" doesn't flip

### What is the expected behavior?
"Flipping popper" flip

### What went wrong?
"Flipping popper" doesn't flip
Please, check zipped .flv file
[2019-10-21 17-39-30.zip](https://github.com/FezVrasta/popper.js/files/3754807/2019-10-21.17-39-30.zip)

### Any other comments?
It works properly if I use: 
flip: { behavior: ['left', 'right'] },
instead of
flip: { behavior: ['left-start', 'right-start'] },

https://codepen.io/vovaltus/pen/oNNYRKb?editors=0010
Please, check zipped .flv file
[2019-10-21 17-40-30.zip](https://github.com/FezVrasta/popper.js/files/3754820/2019-10-21.17-40-30.zip)

Maybe it corresponds to https://github.com/FezVrasta/popper.js/issues/512 and https://github.com/FezVrasta/popper.js/pull/754 but without documentation or explanation, I can't understand how I can solve it.

Appreciated for help.

**Comment by NemoDima** [comment]
@FezVrasta please look at this issue.
I'll be very appreciated.
Regards, Dmytro

**Comment by FezVrasta** [comment]
It looks like it works even if you define `['left', 'right-start']`. It could be a valid workaround for you.

I'm not sure why this is happening, it looks like a bug.

**Comment by NemoDima** [comment]
Thank you a lot!
