### ISSUE TITLE
[next] Implement DEV-only messaging

### ISSUE THREAD

**Issue by atomiks** [popperjs/popper.js#841]
```js
if (__DEV__) {
  console.warn(...);
}
```

https://www.npmjs.com/package/babel-plugin-dev-expression

This way warnings don't end up in production bundles.

**Comment by atomiks** [comment]
@FezVrasta if you want, I can work on a PR for this

**Comment by FezVrasta** [comment]
I think Rollup/Microbundle supports the variable substitution already, we don’t need the babel plugin.

But yep the overall idea is good 👌

**Comment by atomiks** [comment]
How does `concurrently 'yarn dev:serve' 'yarn dev:bundles --watch` work? Using Rollup? I know `rollup-plugin-replace` will work for us if that's the case
