### ISSUE TITLE
[next] ES version, Babel loose mode, ponyfills

### ISSUE THREAD

**Issue by atomiks** [popperjs/popper.js#846]
## ES versions

Looks like this may be a technique we can use for this package: https://twitter.com/_developit/status/1197548723523477505

## Babel transpilation

I noticed the spread ponyfill created by Babel is big, we should use `@babel/env` preset with `loose` mode enabled to make Babel's ponyfills as small as possible

## Method ponyfills

Currently we are using `.find()`, `.findIndex()`, `.includes()` methods throughout the codebase. Do we need to use ponyfills for the ES5 version for these methods like v1 does?

None of those are from ES2018 or later, but I'm not sure how to handle non-syntax features for our ES2017 bundle either. I don't think the ecosystem does "auto-polyfilling" properly yet, only syntax transpilation. So we might need ponyfills for methods.

**Comment by FezVrasta** [comment]
I don't plan to support Internet Explorer for the new version, all the other browsers support `.find`, `.findIndex` and `.includes`. So that means we don't need any polyfill/ponyfill.

If people need to support older browser versions I'd ask them to polyfill the missing methods, I think it's the most reasonable solution.

**Comment by atomiks** [comment]
Not supporting IE11 might be controversial. I mean not supporting it at all, rather than needing to add polyfills (which is fine)

**Comment by FezVrasta** [comment]
Let's see how it goes, I don't want to bloat the library with hacks just to support that terrible piece of software. IE11 wasn't that bad compared to older versions, so everything may work as is.

**Comment by atomiks** [comment]
From what I see IE10 is the main problem in v1 (which is irrelevant now). IE11 has almost no quirks to fix from what I see, so it should be relatively easy
