### ISSUE TITLE
Setup new documentation website

### ISSUE THREAD

**Issue by FezVrasta** [popperjs/popper.js#847]
I would like to use Gatsby for the new documentation website, so that we can easily show examples, and write documentation manually.

I don't want to use JSDocs anymore, since the project now uses Flow, it should be trivial to read the type annotations for people that want to know more.

Also, I received a lot of feedbacks from people that couldn't understand how to use the library from the auto-generated JSDoc documentation. So I think it's better to maintain it by hand.

Any help to set it up would be great!

**Comment by atomiks** [comment]
Willing to work on this if you want!

**Comment by FezVrasta** [comment]
That would be great, thanks!
