### ISSUE TITLE
Arrow Position (Right)

### ISSUE THREAD

**Issue by BrandonWeber** [popperjs/popper.js#848]
Firstly, thanks for the great position engine.

I read all the documentation and found the `data.offsets.arrow.left` value. But it seems that this does not solve my problem, by default the position of the arrow is central (`left` is automatically calculated). I need to move it to the right under the referring element. Perhaps there is still some way to change the positioning of the arrow?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
