### ISSUE TITLE
Popper misaligned if it has initially a display value of none.

### ISSUE THREAD

**Issue by ilyes-ferchiou** [popperjs/popper.js#850]
### CodePen demo

https://codepen.io/ilyesfer/pen/QWWPxap

### Steps to reproduce the problem

1.  Click the #ref div (red).

### What is the expected behavior?

Popper should be horizontally centered to its reference

### What went wrong?

Popper is misaligned

### Any other comments?

If you remove the "display:none" property from the popper CSS. It is aligned correctly.

Tested on Firefox and Chrome.

**Comment by FezVrasta** [comment]
Popper.js can’t compute the popper position if the  element is not rendered in the document, there’s no way to avoid this limitation unfortunately.

You should call sheduleUpdate once the element is visible
