### ISSUE TITLE
Bootstrap 4.4.0 requires popper.js >= 1.16.0 which is not yet published to nuget.org

### ISSUE THREAD

**Issue by ggoodfrd** [popperjs/popper.js#860]
### Steps to reproduce the problem

1.  Use Visual Studio (2019) to install the latest version of Bootstrap (version 4.4.0) via nuget and get an error message that it depends on popper.js version greater than or equal to 1.16.0
2.  Uninstall local popper.js and Boostrap installations via nuget manager
3.  Try to reinstall the latest version of popper.js via nuget manager and discover that the latest stable release available on nuget.org is only version 1.14.3

### What is the expected behavior?

I expected that the nuget.org repository would have the same versions that are released here in GitHub

### What went wrong?

I could not install Boostrap 4.4.0 via nuget because I could not install the popper.js 1.16.0 dependency via nuget

https://www.nuget.org/packages/popper.js/

**Comment by iCptHook** [comment]
Same issue, up!

**Comment by supergibbs** [comment]
In the meantime, ignore dependencies and manually setup popper:
![image](https://user-images.githubusercontent.com/1106331/69743446-4b9e8a00-10f3-11ea-9c5f-fbb76b02d9aa.png)

**Comment by ggoodfrd** [comment]
Good suggestion and I wasn't aware of that option until you pointed it out! In this case I'm working on a team template in which we'd prefer to use the standard dependency settings and not have to configure custom bundles to work around the issue. Will await the new nuget packages before completing my new template, but good to know this is a possible work-around. Thanks!

**Comment by EgilNextron** [comment]
FezVrasta are you no longer using NuGet to distribute Popper.js? Last updated 4/4/2018  Latest version: 1.14.3 is pretty far behind :O

**Comment by yijuneasy** [comment]
nuget

**Comment by FezVrasta** [comment]
Published! https://www.nuget.org/packages/popper.js/1.16.0

Just be careful, Popper v2 will not support NuGet or Bower, just npm and unpkg CDN.

![tenor](https://user-images.githubusercontent.com/5382443/69870096-1a6ab900-12af-11ea-8788-30448aac82cd.gif)

**Comment by ggoodfrd** [comment]
Thanks for getting this updated so quickly. It's all working for me now and was able to complete my task.
