### ISSUE TITLE
[BUG] Too many pop-ups affect performance

### ISSUE THREAD

**Issue by Linkontoask** [popperjs/popper.js#907]
### CodePen demo

[https://codepen.io/linkontoask/pen/RwNgyvm](https://codepen.io/linkontoask/pen/RwNgyvm)

### What went wrong?

The frame is no longer visible, but its position is still being calculated. In the case of many frames, some performance will be affected

**Comment by FezVrasta** [comment]
May you try with @popperjs/core@alpha? You can find it’s documentation on the “next” branch

**Comment by Linkontoask** [comment]
Is there a document similar to the official website? I found only the most basic usage, and the code of the next branch did not solve the problem I said

**Comment by atomiks** [comment]
I don't think the code in `@next` will solve it. I'm not sure if it can really be solved at all? We'd have to bail out of calculations and DOM writes if none of the poppers are visible, but to know that, we need to make the calculations

**Comment by Linkontoask** [comment]
## Restore steps

[https://codepen.io/linkontoask/pen/RwNgyvm](https://codepen.io/linkontoask/pen/RwNgyvm)

1, Click on the visible button
2, Scrolling the browser again will find that the element whose display is `none` is still dynamically calculated.

**Comment by atomiks** [comment]
> 2, Scrolling the browser again will find that the element whose display is none is still dynamically calculated.

We can bail out if we find the popper's dimensions are `0 x 0` but I don't see how that will help your original CodePen. What you can do is call `.disableEventListeners()` when the poppers aren't visible, but how do you know when to hide them?

**Comment by Linkontoask** [comment]
I found that there was no suitable time to destroy the monitor

THX
