### ISSUE TITLE
SVGElement reference and popper type

### ISSUE THREAD

**Issue by HHogg** [popperjs/popper.js#917]
https://github.com/popperjs/popper.js/blob/85bb11cec69f680bf2c0e0dca4b0d219aefb95fc/src/index.js#L51-L52

Could the type for the `reference` and  `popper` element be `Element`? I'm using an `<svg>` element for the reference element which causes typescript warnings. 

Following question, if not any SVG element, how about just `SVGSVGElement` in there too?

**Comment by FezVrasta** [comment]
Flow unfortunately doesn’t support SVGElement right now. I need to find a workaround to at least a make the TS types use it
