### ISSUE TITLE
Unproper position on first load in popper.js v2

### ISSUE THREAD

**Issue by mrpsiho** [popperjs/popper.js#923]
### CodePen demo
https://codepen.io/mrpsiho/pen/VwYQxvw

### Steps to reproduce the problem
The demo uses three elements: two refs and one pop.

1.  Change the id from 'refid1' to 'refid2' (or vise versa) in this code:
const refId = document.getElementById('refid1');

Do no do any other actions, just wait until the main section is getting reloaded. It is clearly seen that pop is slightly displaced on the left.

2.  Scroll the main section, even a bit, and pop is getting re-positioned and becomes perfectly centered.

### What is the expected behavior?

Pop is perfectly centered on first page load.

### What went wrong?

Pop is a bit displaced on the left.

### Any other comments?

Nothing.

**Comment by atomiks** [comment]
Poppers now require you add this CSS before load:

```css
#popper {
  position: absolute;
  left: 0;
  top: 0;
}
```

**Comment by mrpsiho** [comment]
@atomiks Indeed it solves the issue! Thanks! I must be was not attentive enough to this info in the docs!

**Comment by FezVrasta** [comment]
It's not in the docs 🤓

**Comment by atomiks** [comment]
You won't need to do that in `alpha.4`

🤓
