### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by coderkoala** [popperjs/popper.js#928]
[Popperjs](https://popper.js.org/) site right now is throwing a 404, just letting you guys know!

Marvelous library, can't praise it enough from a guy that hates implementing tooltips, only peeved that I can't seem to access the website docs for some reason :)

![image](https://user-images.githubusercontent.com/30156167/72208310-39bd4e80-34c9-11ea-8ec1-ff0f3765763e.png)

**Comment by coderkoala** [comment]
Apparently it's up already! :D 

yay :D

**Comment by FezVrasta** [comment]
Hey! Sorry for the downtime, I didn't expect anyone to notice that 😂

I just flipped the switch to publish all the Popper v2 content and published to npm the first RC.

**Comment by coderkoala** [comment]
@FezVrasta it looks even more vibrant now, thanks for all the dedication and time you put in 🍾 :)

**Comment by FezVrasta** [comment]
Thank @atomiks for the website, he did most of the work!
