### ISSUE TITLE
No Typescript definitions for @popperjs/core/lib/popper-lite

### ISSUE THREAD

**Issue by cuberoot** [popperjs/popper.js#934]
I am trying out rc1 and am following [these directions](https://popper.js.org/docs/tree-shaking) from the documentation.

When I import`@popperjs/core/lib/popper-lite`, I do not get any Typescript definitions.

I have worked around that by adding the following `global.d.ts` to my project:

    declare module '@popperjs/core/lib/popper-lite' {
        export * from '@popperjs/core/dist/typescript/popper-lite';
        export * from '@popperjs/core/dist/typescript/types';
        export * from '@popperjs/core/dist/typescript/enums';
        export var defaultModifiers: Modifier[];
    }

    declare module '@popperjs/core/lib/modifiers/flip' {
        export * from '@popperjs/core/dist/typescript/modifiers/flip.d.ts';
    }

    declare module '@popperjs/core/lib/modifiers/preventOverflow' {
        export * from '@popperjs/core/dist/typescript/modifiers/preventOverflow.d.ts';
    }

**Comment by FezVrasta** [comment]
What would be the proper way to tell TS to consume the `index.d.ts` for popper-lite? I thought TS looked for the root `index.d.ts`  file automatically...

**Comment by atomiks** [comment]
Issue: https://github.com/microsoft/TypeScript/issues/8305

It doesn't seem like TS can find the types for submodules...  doesn't seem like there's a good solution either. Maybe we have to recommend the method @cuberoot has done for this to work.

**Comment by FezVrasta** [comment]
This should be fixed with 668932218abc64226a753d13a61412a46d7f27c8
