### ISSUE TITLE
need a download package

### ISSUE THREAD

**Issue by bill-nuage** [popperjs/popper.js#935]
Hello,

I would like to use this in my salesforce app however due to their stringent security, I can only access js and css that are uploaded into my salesforce org, I cannot use a CDN.

Is there a way I can get a distro of this?

Thanks!

**Comment by FezVrasta** [comment]
I'm always astonished by how many bad practices SalesForce encourages within their products.

As explained in the documentation, we don't recommend direct-download:
https://popper.js.org/docs#3-direct-download

You can always download from the CDN if you really want to.
