### ISSUE TITLE
inline style not allowed with Content-Security-Policy style-src 'self'

### ISSUE THREAD

**Issue by RemcoBlok** [popperjs/popper.js#936]
Popper.js adds an inline style attribute to the container of the popper like
```
<div class="popper" id="example3popper1" x-placement="bottom" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(154px, 269px, 0px);">
...
</div>
```
When the html response contains a Content-Security-Policy http header with style-src 'self' this inline style is not allowed. I cannot change the style-src to 'unsafe-inline' in the Content-Security-Policy http header. Is it possible to make popper.js work without the inline style? 
Note, I'm using popper.js in ngx-bootstrap.

**Comment by FezVrasta** [comment]
You can replace the applyStyles modifier with your own code. But out of the box I don’t see how we could fix that, we need to alter the DOM to apply the styles
