### ISSUE TITLE
Access to older documentation?

### ISSUE THREAD

**Issue by akrikos** [popperjs/popper.js#939]
Hi there! It appears that the main site (https://popper.js.org/) has switched to 2.0 doc. And with the org name change, the previous version documentation is not accessible unless I want to read the raw HTML in the repo. The link to the docs on npmjs.com is "https://github.com/FezVrasta/popper.js/blob/HEAD/docs/_includes/popper-documentation.md" and that forwards me to "https://github.com/popperjs/popper.js/blob/HEAD/docs/_includes/popper-documentation.md".

Am I missing some easy fix here that I can do on my end?

**Comment by FezVrasta** [comment]
The link in the documentation website is https://github.com/popperjs/popper.js/blob/v1.x/docs/_includes/popper-documentation.md, which is just a rendered markdown document, it should be easily readable.

**Comment by akrikos** [comment]
Many thanks! I'd totally skimmed by that small link.
