### ISSUE TITLE
Doesn't position correctly with image maps

### ISSUE THREAD

**Issue by atomiks** [popperjs/popper.js#949]
v1: https://jsfiddle.net/khp36yn9/
v2: https://jsfiddle.net/khp36yn9/1/

Anyone know why these elements are different?

**Comment by FezVrasta** [comment]
HTML maps don't create actual bounding boxes, they are more like the `<datalist />`, they enhance the associated HTML element.

I don't think it's worth supporting them, considering a very few people use them.

One can always extend the built-in `popperOffsets` modifier to add this feature.

**Comment by maximilianh** [comment]
Sadly, this kills tippy for my project. I don't know what "One can always extend the built-in popperOffsets modifier to add this feature." means.
